// ============================================================
// Section 14 - Tableau Dashboard: DAX Measures
// Converted from: Section 14 - Tableau Dashboard.twb
// ============================================================

// ------------------------------------------------------------
// Calculated Fields
// ------------------------------------------------------------

// Tableau: [Category] (alias - shortened display name)
// In Power BI: Use display folder or column rename
Category Short =
    Orders[Category]

// Tableau: [Sales] < 400 (boolean flag for conditional formatting)
Logic 400 =
    IF(Orders[Sales] < 400, TRUE(), FALSE())

// Tableau: [Country] (alias - shortened display name)
// In Power BI: Use display folder or column rename
Country Short =
    Orders[Country]

// Supporting measures for dashboard
Total Sales =
    SUM(Orders[Sales])

Total Profit =
    SUM(Orders[Profit])

Total Quantity =
    SUM(Orders[Quantity])

Profit Ratio =
    DIVIDE(SUM(Orders[Profit]), SUM(Orders[Sales]), 0)
