// =============================================
// SECTION 14 - TABLEAU DASHBOARD - TMDL MODEL
// Tabular Model Definition Language
// Source: course/tableau-files/Section 14 - Tableau Dashboard.twbx
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    table Orders
        lineageTag: sec14-orders

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Row ID", Int64.Type},
                        {"Order ID", type text},
                        {"Order Date", type date},
                        {"Ship Date", type date},
                        {"Ship Mode", type text},
                        {"Customer ID", type text},
                        {"Segment", type text},
                        {"Country", type text},
                        {"City", type text},
                        {"State", type text},
                        {"Postal Code", Int64.Type},
                        {"Region", type text},
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number}
                    })
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer ID

        column Segment
            dataType: string
            summarizeBy: none
            sourceColumn: Segment

        column Country
            dataType: string
            summarizeBy: none
            sourceColumn: Country

        column City
            dataType: string
            summarizeBy: none
            sourceColumn: City

        column State
            dataType: string
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            summarizeBy: none
            sourceColumn: Postal Code

        column Region
            dataType: string
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Product ID

        column Category
            dataType: string
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Product Name

        column Sales
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            summarizeBy: sum
            sourceColumn: Sales

        column Quantity
            dataType: int64
            summarizeBy: sum
            sourceColumn: Quantity

        column Discount
            dataType: double
            formatString: 0.00%
            summarizeBy: average
            sourceColumn: Discount

        column Profit
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            summarizeBy: sum
            sourceColumn: Profit

        // Calculated columns
        // Tableau: [Category] alias
        column 'Category Short'
            dataType: string
            expression: Orders[Category]

        // Tableau: [Sales] < 400
        column 'Logic 400'
            dataType: boolean
            expression: Orders[Sales] < 400

        // Tableau: [Country] alias
        column 'Country Short'
            dataType: string
            expression: Orders[Country]

        // Measures
        measure 'Total Sales' =
            SUM(Orders[Sales])

        measure 'Total Profit' =
            SUM(Orders[Profit])

        measure 'Total Quantity' =
            SUM(Orders[Quantity])

        measure 'Profit Ratio' =
            DIVIDE(SUM(Orders[Profit]), SUM(Orders[Sales]), 0)

        hierarchy 'Geography'
            level Country
                column: Orders[Country]
            level State
                column: Orders[State]
            level City
                column: Orders[City]

    table Customers
        lineageTag: sec14-customers

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Customer ID", type text},
                        {"Customer Name", type text}
                    })
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer Name

    table Products
        lineageTag: sec14-products

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text}
                    })
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Product Name

    table 'Date'
        lineageTag: sec14-date
        dataCategory: Time

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            isKey: true
            expression: CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Year
            dataType: int64
            expression: YEAR('Date'[Date])

        column Month
            dataType: int64
            expression: MONTH('Date'[Date])

        column 'Month Name'
            dataType: string
            expression: FORMAT('Date'[Date], "MMMM")

        column Quarter
            dataType: string
            expression: "Q" & FORMAT(QUARTER('Date'[Date]), "0")

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: 'Date'
        toColumn: Date
