// =============================================
// SECTION 12 — AGGREGATE CALCULATIONS — DAX MEASURES
// Converted from Tableau calculated fields
// Source: course/tableau-files/Section 11 -  Attribute.twbx
// =============================================

// -----------------------------------------------
// CALCULATED FIELDS / MEASURES
// -----------------------------------------------

// Tableau: SUM([Sales])
Total Sales = 
    SUM(Orders[Sales])

// Tableau: AVG([Sales])
 Avg. Sales = 
    AVERAGE(Orders[Sales])

// Tableau: COUNT([Order_ID])
Nr. of Orders = 
    COUNT(Orders[Order_ID])

// Tableau: COUNTD([Product_ID])
Nr. Of Products = 
    DISTINCTCOUNT(Orders[Product_ID])

// Tableau: MAX([Sales])
Highest Sales = 
    MAX(Orders[Sales])

// Tableau: MIN([Sales])
Lowest Sales = 
    MIN(Orders[Sales])

// Tableau: ATTR([Postal_Code])
Attr(Postal Code) = 
    // Original Tableau: ATTR([Postal_Code])
    // DAX equivalent (manual review recommended)
    SUM(Orders[Sales])
