// =============================================================
// SECTION 12 — ROW LEVEL CALCULATIONS (FUNCTIONS) — DAX MEASURES
// Converted from Tableau calculated fields
// Source: Section 12 - Row Level Calculations (Functions).twb
// Data Sources: ProductsLowQuality, Small Data Source, Big Data Source
// =============================================================

// -----------------------------------------------
// STRING FUNCTIONS
// -----------------------------------------------

// #1 — Tableau: LOWER([Product1])
Products (Lower) =
    LOWER(ProductsLowQuality[Product1])

// #2 — Tableau: UPPER([Product1])
Products (Upper) =
    UPPER(ProductsLowQuality[Product1])

// #3 — Tableau: LEN([Calculation_2424625480256524311])
// References Products (Trim) calc field
Products (Len) =
    LEN(TRIM(ProductsLowQuality[Product2]))

// #4 — Tableau: TRIM([Product2])
Products (Trim) =
    TRIM(ProductsLowQuality[Product2])

// #5 — Tableau: COUNTD(TRIM([Product2]))
Products (CountD) =
    CALCULATE(
        DISTINCTCOUNT(ProductsLowQuality[Product2]),
        ALLEXCEPT(ProductsLowQuality, ProductsLowQuality[Product2])
    )

// #6 — Tableau: REPLACE([Product_Name], "#", "Nr.")
Product (Replace) =
    SUBSTITUTE(Products[Product Name], "#", "Nr.")

// #7 — Tableau: STARTSWITH([Product_Name], "Apple")
Products (Startswith Apple) =
    LEFT(Products[Product Name], 5) = "Apple"

// #8 — Tableau: CONTAINS([Product_Name], "Apple")
Products (Contains Apple) =
    SEARCH("Apple", Products[Product Name], 1, 0) > 0

// #9 — Tableau: ENDSWITH([Product_Name], "Apple")
Products (Endswith Apple) =
    RIGHT(Products[Product Name], 5) = "Apple"

// #10 — Tableau: CONTAINS([Product_Name], "Samsung")
Products (Contains Samsung) =
    SEARCH("Samsung", Products[Product Name], 1, 0) > 0

// #11 — Tableau: CONTAINS(LOWER([Product_Name]), "black")
Products (Black) =
    SEARCH("black", LOWER(Products[Product Name]), 1, 0) > 0

// #12 — Tableau: [First_Name] + "-" + [Last_Name]
Full Name =
    Customers[First Name] & "-" & Customers[Last Name]

// #13 — Tableau: [Category] + ": " + [Product_Name]
Full Product Name =
    Products[Category] & ": " & Products[Product Name]

// #14 — Tableau: SPLIT([Phone], "-", 1)
Phone (Country Code) =
    VAR PhoneVal = Customers[Phone]
    VAR Pos1 = SEARCH("-", PhoneVal, 1, 0)
    RETURN IF(Pos1 > 0, LEFT(PhoneVal, Pos1 - 1), PhoneVal)

// #15 — Tableau: SPLIT([Phone], "-", 2)
Phone (Area Code) =
    VAR PhoneVal = Customers[Phone]
    VAR Pos1 = SEARCH("-", PhoneVal, 1, 0)
    VAR Pos2 = SEARCH("-", PhoneVal, Pos1 + 1, 0)
    RETURN IF(Pos2 > 0, MID(PhoneVal, Pos1 + 1, Pos2 - Pos1 - 1), BLANK())

// #16 — Tableau: SPLIT([Phone], "-", 3) + "-" + SPLIT([Phone], "-", 4)
Phone (Number) =
    VAR PhoneVal = Customers[Phone]
    VAR Pos1 = SEARCH("-", PhoneVal, 1, 0)
    VAR Pos2 = SEARCH("-", PhoneVal, Pos1 + 1, 0)
    VAR Pos3 = SEARCH("-", PhoneVal, Pos2 + 1, 0)
    VAR Part3 = IF(Pos3 > 0, MID(PhoneVal, Pos2 + 1, Pos3 - Pos2 - 1), MID(PhoneVal, Pos2 + 1, LEN(PhoneVal)))
    VAR Part4 = IF(Pos3 > 0, MID(PhoneVal, Pos3 + 1, LEN(PhoneVal)), "")
    RETURN IF(LEN(Part4) > 0, Part3 & "-" & Part4, Part3)

// #17 — Tableau: REPLACE(REPLACE([Phone], "+", "00"), "-", "")
Phone (Replace) =
    SUBSTITUTE(SUBSTITUTE(Customers[Phone], "+", "00"), "-", "")

// #18 — Tableau: MID([Address], 9)
Address (Street) =
    MID(Customers[Address], 9, LEN(Customers[Address]))

// #19 — Tableau: MID([Product_Image], 9)
URL (Domain) =
    MID(Products[Product Image], 9, LEN(Products[Product Image]))

// #20 — Tableau: LEFT([Product_Image], 5)
URL (Protocoll) =
    LEFT(Products[Product Image], 5)

// #21 — Tableau: LEFT([Phone], FIND([Phone], "-")-1)
Phone (Country Code Find) =
    LEFT(Customers[Phone], SEARCH("-", Customers[Phone], 1, 0) - 1)

// #22 — Tableau: FIND([Phone], "-")
Phone (Find -) =
    SEARCH("-", Customers[Phone], 1, 0)

// #23 — Tableau: FINDNTH([Phone], "-", 1)
Phone (FindNth2) =
    SEARCH("-", Customers[Phone], 1, 0)

// #24 — Tableau: LOWER([Product_Name])
Products L =
    LOWER(Products[Product Name])

// #25 — Tableau: UPPER([Product_Name])
Products U =
    UPPER(Products[Product Name])

// #26 — Tableau: RIGHT([Product_Image], 3)
URL (Extension) =
    RIGHT(Products[Product Image], 3)

// -----------------------------------------------
// DATE FUNCTIONS
// -----------------------------------------------

// #27 — Tableau: DATEDIFF("day", [Order_Date], [Shipping_Date])
Days to Ship =
    DATEDIFF(Orders[Order Date], Orders[Ship Date], DAY)

// #28 — Tableau: LEFT(DATENAME("month", [Order_Date]), 3)
Order Date (Month) =
    LEFT(FORMAT(Orders[Order Date], "MMMM"), 3)

// #29 — Tableau: DATE(DATETRUNC("month", [Order_Date]))
Order Date (Trunc) =
    STARTOFMONTH(Orders[Order Date])

// #30 — Tableau: DATEADD("year", 2, [Shipping_Date])
Shipping Date (+2 Years) =
    EDATE(Orders[Ship Date], 24)

// #31 — Tableau: TODAY()
Today =
    TODAY()

// #32 — Tableau: NOW()
Now =
    NOW()

// #33 — Tableau: DATENAME("year", [Order_Date])
Order Date (Year) =
    FORMAT(Orders[Order Date], "YYYY")

// #34 — Tableau: DATENAME("quarter", [Order_Date])
Order Date (Quarter) =
    FORMAT(Orders[Order Date], "Q")

// -----------------------------------------------
// CONDITIONAL / LOGICAL
// -----------------------------------------------

// #35 — Tableau: IF SUM([Sales]) > 200000 THEN "green" ELSEIF > 100000 THEN "organge" ELSE "red" END
KPI (Colors) =
    SWITCH(
        TRUE(),
        SUM(Orders[Sales]) > 200000, "green",
        SUM(Orders[Sales]) > 100000, "orange",
        "red"
    )

// #36 — Tableau: IF [Country] = "Germany" AND [Score] > 50 THEN [Sales] END
Sales (AND) =
    IF(Customers[Country] = "Germany" && Customers[Score] > 50, Orders[Sales], BLANK())

// #37 — Tableau: IF [Country] = "Germany" OR [Country] = "France" THEN [Sales] END
Sales (Country) =
    IF(Customers[Country] = "Germany" || Customers[Country] = "France", Orders[Sales], BLANK())

// #38 — Tableau: IF NOT [Country] = "Germany" THEN [Sales] END
Sales (Not Germany) =
    IF(Customers[Country] <> "Germany", Orders[Sales], BLANK())

// #39 — Tableau: IF [Country] = "Germany" OR [Score] > 50 THEN [Sales] END
Sales (OR) =
    IF(Customers[Country] = "Germany" || Customers[Score] > 50, Orders[Sales], BLANK())

// #40 — Tableau: IF [Country] = "Germany" THEN "DE" END
Country (IF) =
    IF(Customers[Country] = "Germany", "DE", BLANK())

// #41 — Tableau: IF [Country] = "Germany" THEN "DE" ELSE "N/A" END
Country (IF, ELSE) =
    IF(Customers[Country] = "Germany", "DE", "N/A")

// #42 — Tableau: IIF([Country] = "Germany", "DE", "N/A")
Country (IIF) =
    IF(Customers[Country] = "Germany", "DE", "N/A")

// #43 — Tableau: IF [Country] = "Germany" THEN "DE" ELSEIF "France" THEN "FR" ELSEIF "USA" THEN "US" ELSE "N/A" END
Country (IF, ELSE, ELSEIF) =
    SWITCH(
        TRUE(),
        Customers[Country] = "Germany", "DE",
        Customers[Country] = "France", "FR",
        Customers[Country] = "USA", "US",
        "N/A"
    )

// #44 — Tableau: CASE [Country] WHEN "Germany" THEN "DE" WHEN "France" THEN "FR" WHEN "USA" THEN "US" ELSE "N/A" END
Country (Case When) =
    SWITCH(
        Customers[Country],
        "Germany", "DE",
        "France", "FR",
        "USA", "US",
        "N/A"
    )

// #45 — Tableau: IF [Country] = "France" Then "FR" ELSEIF "Germany" THEN "DE" ELSEIF "Italy" THEN "IT" ELSE "US" END
Country (Abb U) =
    SWITCH(
        TRUE(),
        Customers[Country] = "France", "FR",
        Customers[Country] = "Germany", "DE",
        Customers[Country] = "Italy", "IT",
        "US"
    )

// #46 — Tableau: LOWER([Calculation_2424625480234987532])
// References Country (Abb U) calculated field
Country (Abb L) =
    LOWER([Country (Abb U)])

// #47 — Tableau: IF CONTAINS(LOWER([Product_Name]), "apple") THEN "Apple" ELSEIF "samsung" THEN "Samsung" ELSEIF "microsoft" THEN "Microsoft" ELSE "Unknown" END
Companies =
    SWITCH(
        TRUE(),
        SEARCH("apple", LOWER(Products[Product Name]), 1, 0) > 0, "Apple",
        SEARCH("samsung", LOWER(Products[Product Name]), 1, 0) > 0, "Samsung",
        SEARCH("microsoft", LOWER(Products[Product Name]), 1, 0) > 0, "Microsoft",
        "Unknown"
    )

// -----------------------------------------------
// NULL HANDLING
// -----------------------------------------------

// #48 — Tableau: ZN([Profit])
Profit (ZN) =
    IF(ISBLANK(Orders[Profit]), 0, Orders[Profit])

// #49 — Tableau: IFNULL([Profit], 1)
Profit (IFNULL) =
    IF(ISBLANK(Orders[Profit]), 1, Orders[Profit])

// #50 — Tableau: IFNULL([Customer_Email], "unknown")
Customer Email (IFNULL) =
    IF(ISBLANK(Customers[Customer Email]), "unknown", Customers[Customer Email])

// #51 — Tableau: ISNULL([Profit])
Profit (ISNULL) =
    ISBLANK(Orders[Profit])

// -----------------------------------------------
// MATH FUNCTIONS
// -----------------------------------------------

// #52 — Tableau: [Quantity] * [Unit_Price]
Revenue =
    Orders[Quantity] * Orders[Unit Price]

// #53 — Tableau: RUNNING_SUM(SUM([Revenue]))
Running Total Revenue =
    VAR CurrentDate = MAX(Orders[Order Date])
    RETURN
        CALCULATE(
            SUMX(Orders, Orders[Quantity] * Orders[Unit Price]),
            FILTER(ALL(Orders[Order Date]), Orders[Order Date] <= CurrentDate)
        )

// #54 — Tableau: SUM([Revenue])
Total Revenue =
    SUMX(Orders, Orders[Quantity] * Orders[Unit Price])

// #55 — Tableau: CEILING([Sales])
Sales (Ceiling) =
    CEILING(Orders[Sales], 1)

// #56 — Tableau: FLOOR([Sales])
Sales (Floor) =
    FLOOR(Orders[Sales], 1)

// #57 — Tableau: ROUND([Sales])
Sales (Round) =
    ROUND(Orders[Sales], 0)

// #58 — Tableau: ROUND([Sales], 1)
Sales (Round1) =
    ROUND(Orders[Sales], 1)

// -----------------------------------------------
// SPLIT / PARSE FUNCTIONS
// -----------------------------------------------

// #59 — Tableau: TRIM(SPLIT([Phone], "-", 1))
Phone - Split 1 =
    VAR PhoneVal = Customers[Phone]
    VAR Pos1 = SEARCH("-", PhoneVal, 1, 0)
    RETURN TRIM(IF(Pos1 > 0, LEFT(PhoneVal, Pos1 - 1), PhoneVal))

// #60 — Tableau: TRIM(SPLIT([Phone], "-", 2))
Phone - Split 2 =
    VAR PhoneVal = Customers[Phone]
    VAR Pos1 = SEARCH("-", PhoneVal, 1, 0)
    VAR Pos2 = SEARCH("-", PhoneVal, Pos1 + 1, 0)
    RETURN TRIM(IF(Pos2 > 0, MID(PhoneVal, Pos1 + 1, Pos2 - Pos1 - 1), MID(PhoneVal, Pos1 + 1, LEN(PhoneVal))))

// #61 — Tableau: TRIM(SPLIT([Phone], "-", 3))
Phone - Split 3 =
    VAR PhoneVal = Customers[Phone]
    VAR Pos1 = SEARCH("-", PhoneVal, 1, 0)
    VAR Pos2 = SEARCH("-", PhoneVal, Pos1 + 1, 0)
    VAR Pos3 = SEARCH("-", PhoneVal, Pos2 + 1, 0)
    RETURN TRIM(IF(Pos3 > 0, MID(PhoneVal, Pos2 + 1, Pos3 - Pos2 - 1), MID(PhoneVal, Pos2 + 1, LEN(PhoneVal))))

// #62 — Tableau: TRIM(SPLIT([Phone], "-", 4))
Phone - Split 4 =
    VAR PhoneVal = Customers[Phone]
    VAR Pos1 = SEARCH("-", PhoneVal, 1, 0)
    VAR Pos2 = SEARCH("-", PhoneVal, Pos1 + 1, 0)
    VAR Pos3 = SEARCH("-", PhoneVal, Pos2 + 1, 0)
    RETURN TRIM(IF(Pos3 > 0, MID(PhoneVal, Pos3 + 1, LEN(PhoneVal)), ""))

// #63 — Tableau: SPLIT(SPLIT([Product_Image], "://", 2), "/", 1)
Product Image (Domain) =
    VAR UrlVal = Products[Product Image]
    VAR AfterScheme = MID(UrlVal, SEARCH("://", UrlVal, 1, 0) + 3, LEN(UrlVal))
    VAR SlashPos = SEARCH("/", AfterScheme, 1, 0)
    RETURN IF(SlashPos > 0, LEFT(AfterScheme, SlashPos - 1), AfterScheme)

// #64 — Tableau: SPLIT([Product_Image], "#", 2)
Product Image (Fragment) =
    VAR UrlVal = Products[Product Image]
    VAR HashPos = SEARCH("#", UrlVal, 1, 0)
    RETURN IF(HashPos > 0, MID(UrlVal, HashPos + 1, LEN(UrlVal)), BLANK())

// #65 — Tableau: MID(SPLIT(SPLIT([Product_Image], "#", 1), "?", 1), FIND(...))
Product Image (Path) =
    VAR UrlVal = Products[Product Image]
    VAR HashPos = SEARCH("#", UrlVal, 1, 0)
    VAR BeforeHash = IF(HashPos > 0, LEFT(UrlVal, HashPos - 1), UrlVal)
    VAR QPos = SEARCH("?", BeforeHash, 1, 0)
    VAR BeforeQuery = IF(QPos > 0, LEFT(BeforeHash, QPos - 1), BeforeHash)
    VAR SchemeEnd = SEARCH("://", UrlVal, 1, 0) + 3
    VAR FirstSlash = SEARCH("/", UrlVal, SchemeEnd, 0)
    RETURN IF(FirstSlash > 0, MID(BeforeQuery, FirstSlash, LEN(BeforeQuery)), BLANK())

// #66 — Tableau: SPLIT(SPLIT([Product_Image], "#", 1), "?", 2)
Product Image (Query) =
    VAR UrlVal = Products[Product Image]
    VAR HashPos = SEARCH("#", UrlVal, 1, 0)
    VAR BeforeHash = IF(HashPos > 0, LEFT(UrlVal, HashPos - 1), UrlVal)
    VAR QPos = SEARCH("?", BeforeHash, 1, 0)
    RETURN IF(QPos > 0, MID(BeforeHash, QPos + 1, LEN(BeforeHash)), BLANK())

// #67 — Tableau: SPLIT([Product_Image], "://", 1)
Product Image (Scheme) =
    VAR UrlVal = Products[Product Image]
    VAR SchemePos = SEARCH("://", UrlVal, 1, 0)
    RETURN IF(SchemePos > 0, LEFT(UrlVal, SchemePos - 1), BLANK())

// -----------------------------------------------
// BIN DEFINITION
// -----------------------------------------------

// #68 — Tableau: [Calculation_1613977548030509058] (bin on Days to Ship)
// In Power BI, use New Group feature on the Days to Ship column
Days to Ship (bin) =
    VAR DaysVal = DATEDIFF(Orders[Order Date], Orders[Ship Date], DAY)
    RETURN FLOOR(DaysVal, 5)
