// TMDL Semantic Model — Section 12: Row Level Calculations (Functions)
// Generated from .twb XML source

model Model
    culture: en-US

    table Orders
        lineageTag: orders-row-level
        dataCategory: Regular

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Order_ID", type text},
                        {"Customer_ID", type text},
                        {"Product_ID", type text},
                        {"Order_Date", type date},
                        {"Shipping_Date", type date},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number},
                        {"Unit_Price", type number}
                    })
                in
                    ChangedTypes

        column 'Order ID' = Orders[Order_ID]
            dataType: string
            lineageTag: col-order-id

        column 'Customer ID' = Orders[Customer_ID]
            dataType: string
            lineageTag: col-customer-id

        column 'Product ID' = Orders[Product_ID]
            dataType: string
            lineageTag: col-product-id

        column 'Order Date' = Orders[Order_Date]
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: col-order-date

        column 'Ship Date' = Orders[Shipping_Date]
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: col-ship-date

        column Sales
            dataType: decimal
            formatString: #,##0.00
            lineageTag: col-sales

        column Quantity
            dataType: int64
            lineageTag: col-quantity

        column Discount
            dataType: decimal
            lineageTag: col-discount

        column Profit
            dataType: decimal
            formatString: #,##0.00
            lineageTag: col-profit

        column 'Unit Price' = Orders[Unit_Price]
            dataType: decimal
            formatString: #,##0.00
            lineageTag: col-unit-price

        // Calculated columns
        column Revenue = Orders[Quantity] * Orders[Unit Price]
            dataType: decimal
            lineageTag: calc-revenue

        column 'Days to Ship' = DATEDIFF(Orders[Order Date], Orders[Ship Date], DAY)
            dataType: int64
            lineageTag: calc-days-to-ship

        column 'Days to Ship (bin)' = FLOOR(DATEDIFF(Orders[Order Date], Orders[Ship Date], DAY), 5)
            dataType: int64
            lineageTag: calc-days-to-ship-bin

        // Measures
        measure 'Products (Lower)' = LOWER(ProductsLowQuality[Product1])
        measure 'Products (Upper)' = UPPER(ProductsLowQuality[Product1])
        measure 'Products (Len)' = LEN(TRIM(ProductsLowQuality[Product2]))
        measure 'Products (Trim)' = TRIM(ProductsLowQuality[Product2])
        measure 'Products (CountD)' = CALCULATE(DISTINCTCOUNT(ProductsLowQuality[Product2]), ALLEXCEPT(ProductsLowQuality, ProductsLowQuality[Product2]))
        measure 'Product (Replace)' = SUBSTITUTE(Products[Product Name], "#", "Nr.")
        measure 'Products (Startswith Apple)' = LEFT(Products[Product Name], 5) = "Apple"
        measure 'Products (Contains Apple)' = SEARCH("Apple", Products[Product Name], 1, 0) > 0
        measure 'Products (Endswith Apple)' = RIGHT(Products[Product Name], 5) = "Apple"
        measure 'Products (Contains Samsung)' = SEARCH("Samsung", Products[Product Name], 1, 0) > 0
        measure 'Products (Black)' = SEARCH("black", LOWER(Products[Product Name]), 1, 0) > 0
        measure 'Full Name' = Customers[First Name] & "-" & Customers[Last Name]
        measure 'Full Product Name' = Products[Category] & ": " & Products[Product Name]
        measure 'KPI (Colors)' = SWITCH(TRUE(), SUM(Orders[Sales]) > 200000, "green", SUM(Orders[Sales]) > 100000, "orange", "red")
        measure 'Sales (AND)' = IF(Customers[Country] = "Germany" && Customers[Score] > 50, Orders[Sales], BLANK())
        measure 'Sales (Country)' = IF(Customers[Country] = "Germany" || Customers[Country] = "France", Orders[Sales], BLANK())
        measure 'Sales (Not Germany)' = IF(Customers[Country] <> "Germany", Orders[Sales], BLANK())
        measure 'Sales (OR)' = IF(Customers[Country] = "Germany" || Customers[Score] > 50, Orders[Sales], BLANK())
        measure 'Country (IF)' = IF(Customers[Country] = "Germany", "DE", BLANK())
        measure 'Country (IF, ELSE)' = IF(Customers[Country] = "Germany", "DE", "N/A")
        measure 'Country (IIF)' = IF(Customers[Country] = "Germany", "DE", "N/A")
        measure 'Country (IF, ELSE, ELSEIF)' = SWITCH(TRUE(), Customers[Country] = "Germany", "DE", Customers[Country] = "France", "FR", Customers[Country] = "USA", "US", "N/A")
        measure 'Country (Case When)' = SWITCH(Customers[Country], "Germany", "DE", "France", "FR", "USA", "US", "N/A")
        measure 'Country (Abb U)' = SWITCH(TRUE(), Customers[Country] = "France", "FR", Customers[Country] = "Germany", "DE", Customers[Country] = "Italy", "IT", "US")
        measure 'Country (Abb L)' = LOWER([Country (Abb U)])
        measure Companies = SWITCH(TRUE(), SEARCH("apple", LOWER(Products[Product Name]), 1, 0) > 0, "Apple", SEARCH("samsung", LOWER(Products[Product Name]), 1, 0) > 0, "Samsung", SEARCH("microsoft", LOWER(Products[Product Name]), 1, 0) > 0, "Microsoft", "Unknown")
        measure 'Profit (ZN)' = IF(ISBLANK(Orders[Profit]), 0, Orders[Profit])
        measure 'Profit (IFNULL)' = IF(ISBLANK(Orders[Profit]), 1, Orders[Profit])
        measure 'Customer Email (IFNULL)' = IF(ISBLANK(Customers[Customer Email]), "unknown", Customers[Customer Email])
        measure 'Profit (ISNULL)' = ISBLANK(Orders[Profit])
        measure 'Running Total Revenue' = VAR CurrentDate = MAX(Orders[Order Date]) RETURN CALCULATE(SUMX(Orders, Orders[Quantity] * Orders[Unit Price]), FILTER(ALL(Orders[Order Date]), Orders[Order Date] <= CurrentDate))
        measure 'Total Revenue' = SUMX(Orders, Orders[Quantity] * Orders[Unit Price])
        measure 'Sales (Ceiling)' = CEILING(Orders[Sales], 1)
        measure 'Sales (Floor)' = FLOOR(Orders[Sales], 1)
        measure 'Sales (Round)' = ROUND(Orders[Sales], 0)
        measure 'Sales (Round1)' = ROUND(Orders[Sales], 1)
        measure Today = TODAY()
        measure Now = NOW()
        measure 'Order Date (Month)' = LEFT(FORMAT(Orders[Order Date], "MMMM"), 3)
        measure 'Order Date (Trunc)' = STARTOFMONTH(Orders[Order Date])
        measure 'Shipping Date (+2 Years)' = EDATE(Orders[Ship Date], 24)
        measure 'Order Date (Year)' = FORMAT(Orders[Order Date], "YYYY")
        measure 'Order Date (Quarter)' = FORMAT(Orders[Order Date], "Q")

    table Customers
        lineageTag: customers-row-level

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Customer_ID", type text},
                        {"First_Name", type text},
                        {"Last_Name", type text},
                        {"Address", type text},
                        {"Postal_Code", type text},
                        {"City", type text},
                        {"Country", type text},
                        {"Phone", type text},
                        {"Score", Int64.Type}
                    })
                in
                    ChangedTypes

        column 'Customer ID' = Customers[Customer_ID]
            dataType: string
        column 'First Name' = Customers[First_Name]
            dataType: string
        column 'Last Name' = Customers[Last_Name]
            dataType: string
        column Address
            dataType: string
        column 'Postal Code' = Customers[Postal_Code]
            dataType: string
        column City
            dataType: string
        column Country
            dataType: string
        column Phone
            dataType: string
        column Score
            dataType: int64
        column 'Customer Email'
            dataType: string
            description: Joined from Customers_Details.csv via Customer_ID

    table Products
        lineageTag: products-row-level

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Product_ID", type text},
                        {"Product_Name", type text},
                        {"Category", type text},
                        {"Product_Image", type text}
                    })
                in
                    ChangedTypes

        column 'Product ID' = Products[Product_ID]
            dataType: string
        column 'Product Name' = Products[Product_Name]
            dataType: string
        column Category
            dataType: string
        column 'Product Image' = Products[Product_Image]
            dataType: string

    table ProductsLowQuality
        lineageTag: products-low-quality

        partition ProductsLowQuality = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/ProductsLowQuality.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Order_ID", type text},
                        {"Product1", type text},
                        {"Product2", type text},
                        {"Quantity", Int64.Type},
                        {"Price", type number}
                    })
                in
                    ChangedTypes

        column 'Order ID' = ProductsLowQuality[Order_ID]
            dataType: string
        column Product1
            dataType: string
        column Product2
            dataType: string
        column Quantity
            dataType: int64
        column Price
            dataType: decimal

    // Relationships
    relationship Orders_Customers = Orders[Customer ID] -> Customers[Customer ID]
        crossFilteringBehavior: singleDirection

    relationship Orders_Products = Orders[Product ID] -> Products[Product ID]
        crossFilteringBehavior: singleDirection
