// ============================================================
// Section 13 – Tableau 63 Charts: DAX Measures
// Converted from: Tableau Charts  60 Visuals Without Format.twb
// ============================================================

// ------------------------------------------------------------
// Parameter Tables
// ------------------------------------------------------------

// Parameter: Select Country (string, default "USA")
Select Country = GENERATESERIES(1, 1, 1)  // Placeholder – populate with distinct country values

Select Country Value = SELECTEDVALUE('Select Country'[Select Country], "USA")

// Parameter: Select Discount (real, default 0.18)
Select Discount = GENERATESERIES(0, 1, 0.01)

Select Discount Value = SELECTEDVALUE('Select Discount'[Select Discount], 0.18)

// Parameter: Select Profit Ratio (real, default 0.1)
Select Profit Ratio = GENERATESERIES(-1, 1, 0.01)

Select Profit Ratio Value = SELECTEDVALUE('Select Profit Ratio'[Select Profit Ratio], 0.1)

// ------------------------------------------------------------
// Calculated Fields
// ------------------------------------------------------------

// Tableau: [Country] = [Parameters].[Parameter 1]
Highlighted Country = 
    IF(Orders[Country] = [Select Country Value], TRUE(), FALSE())

// Tableau: IF YEAR([Order_Date]) = 2021 THEN [Sales] END
Sales 2021 = 
    CALCULATE(
        SUM(Orders[Sales]),
        YEAR(Orders[Order Date]) = 2021
    )

// Tableau: IF YEAR([Order_Date]) = 2022 THEN [Sales] END
Sales 2022 = 
    CALCULATE(
        SUM(Orders[Sales]),
        YEAR(Orders[Order Date]) = 2022
    )

// Tableau: { FIXED [Customer_ID] : COUNT([Order_ID])}
Nr of Orders per Customer = 
    CALCULATE(
        COUNT(Orders[Order ID]),
        ALLEXCEPT(Orders, Orders[Customer ID])
    )

// Tableau: SUM([Profit])/SUM([Sales])
Profit Ratio = 
    DIVIDE(
        SUM(Orders[Profit]),
        SUM(Orders[Sales]),
        0
    )

// Tableau: IF [Profit Ratio] >= [Param3] AND AVG([Discount]) <= [Param2] THEN "Green" ...
Quadrant Color = 
    SWITCH(
        TRUE(),
        [Profit Ratio] >= [Select Profit Ratio Value] && AVERAGE(Orders[Discount]) <= [Select Discount Value], "Green",
        [Profit Ratio] >= [Select Profit Ratio Value] && AVERAGE(Orders[Discount]) > [Select Discount Value], "Orange",
        [Profit Ratio] < [Select Profit Ratio Value] && AVERAGE(Orders[Discount]) <= [Select Discount Value], "Yellow",
        "Red"
    )

// Tableau: IF SUM([Sales]) > 50000 THEN "Green" ELSEIF SUM([Sales]) <= 50000 AND SUM([Sales]) > 20000 THEN "Orange" ELSE "Red" END
KPI Colors = 
    SWITCH(
        TRUE(),
        SUM(Orders[Sales]) > 50000, "Green",
        SUM(Orders[Sales]) > 20000, "Orange",
        "Red"
    )

// Tableau: Compares Sales 2021 vs Sales 2022 for color coding
KPI Colors of Two Years = 
    IF(
        [Sales 2022] >= [Sales 2021],
        "Green",
        "Red"
    )

// Tableau: [Quantity] (bin, size = 10)
// In Power BI: Create a calculated column or use binning in visual
Quantity Bin = 
    FLOOR(Orders[Quantity], 10)
