// ============================================================
// Section 15 - Tableau Sales & Customer Dashboards: DAX Measures
// Converted from: Sales & Customer Dashboards (Dynamic).twb
// ============================================================

// ------------------------------------------------------------
// Parameter Table
// ------------------------------------------------------------

// Parameter: Select Year (integer, default 2023)
// Tableau: [Parameters].[Parameter 1] = 2023
// DAX: GENERATESERIES(2020, 2023, 1) + SELECTEDVALUE
Select Year Value =
    SELECTEDVALUE('Select Year'[Select Year], 2023)

// ------------------------------------------------------------
// Year Reference Measures
// ------------------------------------------------------------

// Tableau: [Parameters].[Parameter 1]
Current Year =
    [Select Year Value]

// Tableau: [Parameters].[Parameter 1]-1
Previous Year =
    [Select Year Value] - 1

// Tableau: YEAR([Order Date])
Order Date Year =
    YEAR(Orders[Order Date])

// ------------------------------------------------------------
// Current Year (CY) Measures
// ------------------------------------------------------------

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1] THEN [Sales] END
CY Sales =
    CALCULATE(
        SUM(Orders[Sales]),
        YEAR(Orders[Order Date]) = [Select Year Value]
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1] THEN [Profit] END
CY Profit =
    CALCULATE(
        SUM(Orders[Profit]),
        YEAR(Orders[Order Date]) = [Select Year Value]
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1] THEN [Quantity] END
CY Quantity =
    CALCULATE(
        SUM(Orders[Quantity]),
        YEAR(Orders[Order Date]) = [Select Year Value]
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1] THEN [Customer ID] END
CY Customers =
    CALCULATE(
        DISTINCTCOUNT(Orders[Customer ID]),
        YEAR(Orders[Order Date]) = [Select Year Value]
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1] THEN [Order ID] END
CY Orders =
    CALCULATE(
        DISTINCTCOUNT(Orders[Order ID]),
        YEAR(Orders[Order Date]) = [Select Year Value]
    )

// Tableau: SUM([CY Sales]) / COUNTD([CY Customers])
CY Sales per Customer =
    DIVIDE([CY Sales], [CY Customers], 0)

// ------------------------------------------------------------
// Previous Year (PY) Measures
// ------------------------------------------------------------

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1]-1 THEN [Sales] END
PY Sales =
    CALCULATE(
        SUM(Orders[Sales]),
        YEAR(Orders[Order Date]) = [Select Year Value] - 1
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1]-1 THEN [Profit] END
PY Profit =
    CALCULATE(
        SUM(Orders[Profit]),
        YEAR(Orders[Order Date]) = [Select Year Value] - 1
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1]-1 THEN [Quantity] END
PY Quantity =
    CALCULATE(
        SUM(Orders[Quantity]),
        YEAR(Orders[Order Date]) = [Select Year Value] - 1
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1]-1 THEN [Customer ID] END
PY Customers =
    CALCULATE(
        DISTINCTCOUNT(Orders[Customer ID]),
        YEAR(Orders[Order Date]) = [Select Year Value] - 1
    )

// Tableau: IF YEAR([Order Date]) = [Parameters].[Parameter 1]-1 THEN [Order ID] END
PY Orders =
    CALCULATE(
        DISTINCTCOUNT(Orders[Order ID]),
        YEAR(Orders[Order Date]) = [Select Year Value] - 1
    )

// Tableau: SUM([PY Sales]) / COUNTD([PY Customers])
PY Sales per Customer =
    DIVIDE([PY Sales], [PY Customers], 0)

// ------------------------------------------------------------
// Year-over-Year % Difference Measures
// ------------------------------------------------------------

// Tableau: (SUM([CY Sales]) - SUM([PY Sales])) / SUM([PY Sales])
% Diff Sales =
    DIVIDE([CY Sales] - [PY Sales], [PY Sales], 0)

// Tableau: (SUM([CY Profit]) - SUM([PY Profit])) / SUM([PY Profit])
% Diff Profit =
    DIVIDE([CY Profit] - [PY Profit], [PY Profit], 0)

// Tableau: (SUM([CY Quantity]) - SUM([PY Quantity])) / SUM([PY Quantity])
% Diff Quantity =
    DIVIDE([CY Quantity] - [PY Quantity], [PY Quantity], 0)

// Tableau: (COUNTD([CY Customers]) - COUNTD([PY Customers])) / COUNTD([PY Customers])
% Diff Customers =
    DIVIDE([CY Customers] - [PY Customers], [PY Customers], 0)

// Tableau: (COUNTD([CY Orders]) - COUNTD([PY Orders])) / COUNTD([PY Orders])
% Diff Orders =
    DIVIDE([CY Orders] - [PY Orders], [PY Orders], 0)

// Tableau: ([CY Sales per Customer] - [PY Sales per Customer]) / [PY Sales per Customer]
% Diff Sales per Customers =
    DIVIDE([CY Sales per Customer] - [PY Sales per Customer], [PY Sales per Customer], 0)

// ------------------------------------------------------------
// Window Calculation Measures (Min/Max/Avg)
// ------------------------------------------------------------

// Tableau: IF SUM([CY Sales]) = WINDOW_MAX(SUM([CY Sales])) THEN SUM([CY Sales])
//          ELSEIF SUM([CY Sales]) = WINDOW_MIN(SUM([CY Sales])) THEN SUM([CY Sales]) END
Min/Max Sales =
    IF(
        [CY Sales] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Sales]),
        [CY Sales],
        IF(
            [CY Sales] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Sales]),
            [CY Sales],
            BLANK()
        )
    )

// Tableau: IF COUNTD([CY Customers]) = WINDOW_MAX(COUNTD([CY Customers])) ...
Min/Max Customers =
    IF(
        [CY Customers] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Customers]),
        [CY Customers],
        IF(
            [CY Customers] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Customers]),
            [CY Customers],
            BLANK()
        )
    )

// Tableau: IF SUM([CY Quantity]) = WINDOW_MAX(SUM([CY Quantity])) ...
Min/Max Quantity =
    IF(
        [CY Quantity] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Quantity]),
        [CY Quantity],
        IF(
            [CY Quantity] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Quantity]),
            [CY Quantity],
            BLANK()
        )
    )

// Tableau: IF SUM([CY Profit]) = WINDOW_MAX(SUM([CY Profit])) ...
Min/Max Profit =
    IF(
        [CY Profit] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Profit]),
        [CY Profit],
        IF(
            [CY Profit] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Profit]),
            [CY Profit],
            BLANK()
        )
    )

// Tableau: IF COUNTD([CY Orders]) = WINDOW_MAX(COUNTD([CY Orders])) ...
Min/Max Orders =
    IF(
        [CY Orders] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Orders]),
        [CY Orders],
        IF(
            [CY Orders] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Orders]),
            [CY Orders],
            BLANK()
        )
    )

// Tableau: IF [CY Sales per Customer] = WINDOW_MAX([CY Sales per Customer]) ...
Min/Max Sales Per Customers =
    IF(
        [CY Sales per Customer] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Sales per Customer]),
        [CY Sales per Customer],
        IF(
            [CY Sales per Customer] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Sales per Customer]),
            [CY Sales per Customer],
            BLANK()
        )
    )

// ------------------------------------------------------------
// KPI Measures
// ------------------------------------------------------------

// Tableau: IF SUM([CY Sales]) > WINDOW_AVG(SUM([CY Sales])) THEN 'Above' ELSE 'Below' END
KPI Sales Avg =
    IF(
        [CY Sales] > AVERAGEX(ALLSELECTED(Orders[Sub-Category]), [CY Sales]),
        "Above",
        "Below"
    )

// Tableau: IF SUM([CY Profit]) > WINDOW_AVG(SUM([CY Profit])) THEN 'Above' ELSE 'Below' END
KPI Profit Avg =
    IF(
        [CY Profit] > AVERAGEX(ALLSELECTED(Orders[Sub-Category]), [CY Profit]),
        "Above",
        "Below"
    )

// Tableau: IF SUM([PY Sales]) < SUM([CY Sales]) THEN circle ELSE '' END
KPI CY Less PY =
    IF([PY Sales] < [CY Sales], UNICHAR(11044), "")

// ------------------------------------------------------------
// LOD Expression Measures
// ------------------------------------------------------------

// Tableau: {SUM([CY Sales])} — Grand total of CY Sales across all dimensions
Grand Total CY Sales =
    CALCULATE([CY Sales], ALL(Orders))

// Tableau: { FIXED [Customer ID]: COUNTD([Order ID]) }
Nr of Orders per Customers =
    CALCULATE(
        DISTINCTCOUNT(Orders[Order ID]),
        ALLEXCEPT(Orders, Orders[Customer ID])
    )
