// =============================================
// SECTION 15 - SALES & CUSTOMER DASHBOARDS - TMDL MODEL
// Tabular Model Definition Language
// Source: course/tableau-files/Sales & Customer Dashboards (Dynamic).twbx
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    table Orders
        lineageTag: sec15-orders

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Row ID", Int64.Type},
                        {"Order ID", type text},
                        {"Order Date", type date},
                        {"Ship Date", type date},
                        {"Ship Mode", type text},
                        {"Customer ID", type text},
                        {"Segment", type text},
                        {"Country", type text},
                        {"City", type text},
                        {"State", type text},
                        {"Postal Code", Int64.Type},
                        {"Region", type text},
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number}
                    })
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer ID

        column Segment
            dataType: string
            summarizeBy: none
            sourceColumn: Segment

        column Country
            dataType: string
            summarizeBy: none
            sourceColumn: Country

        column City
            dataType: string
            summarizeBy: none
            sourceColumn: City

        column State
            dataType: string
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            summarizeBy: none
            sourceColumn: Postal Code

        column Region
            dataType: string
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Product ID

        column Category
            dataType: string
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Product Name

        column Sales
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            summarizeBy: sum
            sourceColumn: Sales

        column Quantity
            dataType: int64
            summarizeBy: sum
            sourceColumn: Quantity

        column Discount
            dataType: double
            formatString: 0.00%
            summarizeBy: average
            sourceColumn: Discount

        column Profit
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            summarizeBy: sum
            sourceColumn: Profit

        // --- ALL DAX MEASURES ---

        measure 'Select Year Value' =
            SELECTEDVALUE('Select Year'[Select Year], 2023)

        measure 'Current Year' = [Select Year Value]

        measure 'Previous Year' = [Select Year Value] - 1

        measure 'Order Date Year' = YEAR(Orders[Order Date])

        measure 'CY Sales' =
            CALCULATE(SUM(Orders[Sales]), YEAR(Orders[Order Date]) = [Select Year Value])

        measure 'CY Profit' =
            CALCULATE(SUM(Orders[Profit]), YEAR(Orders[Order Date]) = [Select Year Value])

        measure 'CY Quantity' =
            CALCULATE(SUM(Orders[Quantity]), YEAR(Orders[Order Date]) = [Select Year Value])

        measure 'CY Customers' =
            CALCULATE(DISTINCTCOUNT(Orders[Customer ID]), YEAR(Orders[Order Date]) = [Select Year Value])

        measure 'CY Orders' =
            CALCULATE(DISTINCTCOUNT(Orders[Order ID]), YEAR(Orders[Order Date]) = [Select Year Value])

        measure 'CY Sales per Customer' =
            DIVIDE([CY Sales], [CY Customers], 0)

        measure 'PY Sales' =
            CALCULATE(SUM(Orders[Sales]), YEAR(Orders[Order Date]) = [Select Year Value] - 1)

        measure 'PY Profit' =
            CALCULATE(SUM(Orders[Profit]), YEAR(Orders[Order Date]) = [Select Year Value] - 1)

        measure 'PY Quantity' =
            CALCULATE(SUM(Orders[Quantity]), YEAR(Orders[Order Date]) = [Select Year Value] - 1)

        measure 'PY Customers' =
            CALCULATE(DISTINCTCOUNT(Orders[Customer ID]), YEAR(Orders[Order Date]) = [Select Year Value] - 1)

        measure 'PY Orders' =
            CALCULATE(DISTINCTCOUNT(Orders[Order ID]), YEAR(Orders[Order Date]) = [Select Year Value] - 1)

        measure 'PY Sales per Customer' =
            DIVIDE([PY Sales], [PY Customers], 0)

        measure '% Diff Sales' = DIVIDE([CY Sales] - [PY Sales], [PY Sales], 0)
        measure '% Diff Profit' = DIVIDE([CY Profit] - [PY Profit], [PY Profit], 0)
        measure '% Diff Quantity' = DIVIDE([CY Quantity] - [PY Quantity], [PY Quantity], 0)
        measure '% Diff Customers' = DIVIDE([CY Customers] - [PY Customers], [PY Customers], 0)
        measure '% Diff Orders' = DIVIDE([CY Orders] - [PY Orders], [PY Orders], 0)
        measure '% Diff Sales per Customers' = DIVIDE([CY Sales per Customer] - [PY Sales per Customer], [PY Sales per Customer], 0)

        measure 'Min/Max Sales' =
            IF([CY Sales] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Sales]), [CY Sales], IF([CY Sales] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Sales]), [CY Sales], BLANK()))

        measure 'Min/Max Customers' =
            IF([CY Customers] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Customers]), [CY Customers], IF([CY Customers] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Customers]), [CY Customers], BLANK()))

        measure 'Min/Max Quantity' =
            IF([CY Quantity] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Quantity]), [CY Quantity], IF([CY Quantity] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Quantity]), [CY Quantity], BLANK()))

        measure 'Min/Max Profit' =
            IF([CY Profit] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Profit]), [CY Profit], IF([CY Profit] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Profit]), [CY Profit], BLANK()))

        measure 'Min/Max Orders' =
            IF([CY Orders] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Orders]), [CY Orders], IF([CY Orders] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Orders]), [CY Orders], BLANK()))

        measure 'Min/Max Sales Per Customers' =
            IF([CY Sales per Customer] = MAXX(ALLSELECTED(Orders[Sub-Category]), [CY Sales per Customer]), [CY Sales per Customer], IF([CY Sales per Customer] = MINX(ALLSELECTED(Orders[Sub-Category]), [CY Sales per Customer]), [CY Sales per Customer], BLANK()))

        measure 'KPI Sales Avg' =
            IF([CY Sales] > AVERAGEX(ALLSELECTED(Orders[Sub-Category]), [CY Sales]), "Above", "Below")

        measure 'KPI Profit Avg' =
            IF([CY Profit] > AVERAGEX(ALLSELECTED(Orders[Sub-Category]), [CY Profit]), "Above", "Below")

        measure 'KPI CY Less PY' =
            IF([PY Sales] < [CY Sales], UNICHAR(11044), "")

        measure 'Grand Total CY Sales' =
            CALCULATE([CY Sales], ALL(Orders))

        measure 'Nr of Orders per Customers' =
            CALCULATE(DISTINCTCOUNT(Orders[Order ID]), ALLEXCEPT(Orders, Orders[Customer ID]))

        hierarchy 'Geography'
            level Country
                column: Orders[Country]
            level State
                column: Orders[State]
            level City
                column: Orders[City]

    // Parameter Table: Select Year
    table 'Select Year'
        lineageTag: sec15-paramyear

        partition 'Select Year' = calculated
            source = GENERATESERIES(2020, 2023, 1)

        column 'Select Year'
            dataType: int64
            summarizeBy: none

    table Customers
        lineageTag: sec15-customers

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Customer ID", type text},
                        {"Customer Name", type text}
                    })
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer Name

    table Products
        lineageTag: sec15-products

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text}
                    })
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Product Name

    table 'Date'
        lineageTag: sec15-date
        dataCategory: Time

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            isKey: true
            expression: CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Year
            dataType: int64
            expression: YEAR('Date'[Date])

        column Month
            dataType: int64
            expression: MONTH('Date'[Date])

        column 'Month Name'
            dataType: string
            expression: FORMAT('Date'[Date], "MMMM")

        column Quarter
            dataType: string
            expression: "Q" & FORMAT(QUARTER('Date'[Date]), "0")

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: 'Date'
        toColumn: Date
