// =============================================
// SECTION 07 — RENAMING — DAX MEASURES
// Converted from Tableau calculated fields
// Source: tableau-source/course/tableau-files/Section 07 - Renaming/extracted/Section 7 - Renaming.twb
// =============================================

// -----------------------------------------------
// CALCULATED FIELDS
// -----------------------------------------------

// Tableau: [Category] (string, named "Category (Short)")
// This is an alias/rename field. In Tableau, it copies the [Category] column
// and applies display aliases: Furniture -> "F", Office Supplies -> "O", Technology -> "T"
// In DAX, use a calculated column with SWITCH to apply the alias mapping.
Category (Short) =
    SWITCH(
        Orders[Category],
        "Furniture", "F",
        "Office Supplies", "O",
        "Technology", "T",
        Orders[Category]
    )

// Tableau: [Sales] < 400 (boolean, named "Logic 400")
// Converted to DAX calculated column on Orders table
Logic 400 = IF(Orders[Sales] < 400, TRUE(), FALSE())

// Tableau: [Country] (string, named "Country (Short)")
// This is an alias/rename field. In Tableau, it copies the [Country] column
// and applies display aliases: France -> "FR", Germany -> "DE"
// In DAX, use a calculated column with SWITCH to apply the alias mapping.
Country (Short) =
    SWITCH(
        Orders[Country],
        "France", "FR",
        "Germany", "DE",
        Orders[Country]
    )
