// =============================================
// SECTION 07 — RENAMING — TMDL MODEL
// Tabular Model Definition Language
// Source: tableau-source/course/tableau-files/Section 07 - Renaming/extracted/Section 7 - Renaming.twb
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    // ===========================================
    // FACT TABLE: Orders
    // ===========================================

    table Orders
        lineageTag: 89f3cae6-a5e9-408f-b166-1ac409fc1ed5

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Row ID", Int64.Type}},
                        {{"Order ID", type text}},
                        {{"Order Date", type date}},
                        {{"Ship Date", type date}},
                        {{"Ship Mode", type text}},
                        {{"Customer ID", type text}},
                        {{"Segment", type text}},
                        {{"Country", type text}},
                        {{"City", type text}},
                        {{"State", type text}},
                        {{"Postal Code", Int64.Type}},
                        {{"Region", type text}},
                        {{"Product ID", type text}},
                        {{"Category", type text}},
                        {{"Sub-Category", type text}},
                        {{"Product Name", type text}},
                        {{"Sales", type number}},
                        {{"Quantity", Int64.Type}},
                        {{"Discount", type number}},
                        {{"Profit", type number}}
                    }})
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            formatString: 0
            lineageTag: d3d03103-ac50-494e-850d-69a860929e0b
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            lineageTag: 2cb6482c-c7cd-476f-a014-8650b3d2751e
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 41f2dfe3-e293-4ad0-9278-1fb5615c3807
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 900833f2-f2cd-4486-9362-49218fa08542
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            lineageTag: 061adbd1-74bc-4f1b-b43c-dcf9c7f5622d
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            lineageTag: d9a6cefa-9049-4717-b75a-089bbefbb4fd
            summarizeBy: none
            sourceColumn: Customer ID

        column Segment
            dataType: string
            lineageTag: 389cd838-233c-4596-b61e-4a80020c2530
            summarizeBy: none
            sourceColumn: Segment

        column Country
            dataType: string
            lineageTag: 576fa16e-b1ed-4aa5-9f89-a99f5b4089b4
            summarizeBy: none
            sourceColumn: Country

        column City
            dataType: string
            lineageTag: c1b3c0cd-7315-4088-a7c4-7995e5a2e949
            summarizeBy: none
            sourceColumn: City

        column State
            dataType: string
            lineageTag: 3ba4f2ae-9dd6-4be4-80fb-3b489804e4a9
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            formatString: 0
            lineageTag: 9a0cd0bd-678c-439b-8037-3f8524abdb0f
            summarizeBy: none
            sourceColumn: Postal Code

        column Region
            dataType: string
            lineageTag: 94724eb1-b2f5-4f19-824b-2344e7dc8a84
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            lineageTag: cffb5bd8-60cc-4b07-b926-55a922bc410a
            summarizeBy: none
            sourceColumn: Product ID

        column Category
            dataType: string
            lineageTag: 9544ae3d-9785-42d8-97ef-65e7a56b0a87
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: 66cab666-0cad-4bb7-b7e0-a5c7b73ea5d1
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: ad91bcf1-1c6f-4fb2-836e-d6f8d0729c9b
            summarizeBy: none
            sourceColumn: Product Name

        column Sales
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: 333226d2-292d-4f6f-8e93-82ae67c0461c
            summarizeBy: sum
            sourceColumn: Sales

        column Quantity
            dataType: int64
            formatString: 0
            lineageTag: bd94dbdd-f908-4b4a-9d96-be17e5a2461c
            summarizeBy: sum
            sourceColumn: Quantity

        column Discount
            dataType: double
            formatString: 0.00%
            lineageTag: 7dd2c986-0f79-4c2a-befd-8b9fa580ad64
            summarizeBy: average
            sourceColumn: Discount

        column Profit
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: 3b5540bd-940d-493b-856a-248d01cba26f
            summarizeBy: sum
            sourceColumn: Profit

        // --- Calculated Column: Category (Short) ---
        // Tableau: [Category] with aliases Furniture->"F", Office Supplies->"O", Technology->"T"
        column 'Category (Short)'
            dataType: string
            lineageTag: b86f3847-d173-4305-bcf7-53c370398e88
            summarizeBy: none
            isDataTypeInferred: true
            expression: SWITCH(Orders[Category], "Furniture", "F", "Office Supplies", "O", "Technology", "T", Orders[Category])

        // --- Calculated Column: Logic 400 ---
        // Tableau: [Sales] < 400 (boolean)
        column 'Logic 400'
            dataType: boolean
            lineageTag: 72075ce3-5563-454e-8667-8100e0d05c89
            summarizeBy: none
            isDataTypeInferred: true
            expression: IF(Orders[Sales] < 400, TRUE(), FALSE())

        // --- Calculated Column: Country (Short) ---
        // Tableau: [Country] with aliases France->"FR", Germany->"DE"
        column 'Country (Short)'
            dataType: string
            lineageTag: db28a836-fbb0-44a8-bc82-69da8cb286a4
            summarizeBy: none
            isDataTypeInferred: true
            expression: SWITCH(Orders[Country], "France", "FR", "Germany", "DE", Orders[Country])

    // ===========================================
    // DIMENSION TABLE: Customers
    // ===========================================

    table Customers
        lineageTag: 912c0b91-be0d-426b-a45f-e1f2fb48bae9

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Customer ID", type text}},
                        {{"Customer Name", type text}}
                    }})
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            lineageTag: c8147639-e0e4-4088-a27d-2d7214da7e64
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            lineageTag: 7d60f92b-7f7d-4dc4-852c-913cc883f607
            summarizeBy: none
            sourceColumn: Customer Name

    // ===========================================
    // DIMENSION TABLE: Products
    // ===========================================

    table Products
        lineageTag: b5aa02ef-b92e-48e4-9e42-ee4198a92425

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Product ID", type text}},
                        {{"Category", type text}},
                        {{"Sub-Category", type text}},
                        {{"Product Name", type text}}
                    }})
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            lineageTag: b3ca6b83-3d64-4ae9-abba-826695ae8b2d
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            lineageTag: 8f81f463-ccd3-4e11-8fb1-ca822aec55e8
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: 6c832481-31e5-4fdb-868d-2b69488b73ca
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: 42ef6710-fa50-43f1-b859-603f8d38ee29
            summarizeBy: none
            sourceColumn: Product Name

    // ===========================================
    // DATE TABLE (DAX-generated calendar)
    // ===========================================

    table Date
        lineageTag: 85092ef7-e6c8-42bb-b334-7e4349025c5f

        partition Date = calculated
            mode: import
            source = CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 1c1324cd-5c24-439c-8731-c919d4f83d43
            summarizeBy: none
            isKey: true

        column Year
            dataType: int64
            formatString: 0
            lineageTag: 88ca070d-618b-4e25-b881-7249464dab65
            summarizeBy: none
            isDataTypeInferred: true
            expression: YEAR([Date])

        column Month
            dataType: int64
            formatString: 0
            lineageTag: 936a436e-f30c-4dfa-ba19-58b9294f6fc1
            summarizeBy: none
            isDataTypeInferred: true
            expression: MONTH([Date])

        column 'Month Name'
            dataType: string
            lineageTag: e5c7064d-2415-4ee1-bd3c-ebff72784cee
            summarizeBy: none
            isDataTypeInferred: true
            expression: FORMAT([Date], "MMMM")

        column Quarter
            dataType: string
            lineageTag: 40d5af3f-bdc2-4558-840c-5485804f1b47
            summarizeBy: none
            isDataTypeInferred: true
            expression: "Q" & FORMAT([Date], "Q")

    // ===========================================
    // RELATIONSHIPS
    // ===========================================

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: singleDirection

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: singleDirection

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: Date
        toColumn: Date
        crossFilteringBehavior: singleDirection
