// =============================================
// SECTION 07 — RENAMING — TMDL MODEL
// Tabular Model Definition Language
// Source: course/tableau-files/Section 7 - Renaming.twbx
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    // ===========================================
    // FACT TABLE: Orders
    // ===========================================

    table Orders
        lineageTag: 7d01f579-efae-e99d-b0a8-7462628b2445

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Row ID", Int64.Type},
                        {"Order ID", type text},
                        {"Order Date", type date},
                        {"Ship Date", type date},
                        {"Ship Mode", type text},
                        {"Customer ID", type text},
                        {"Segment", type text},
                        {"Country", type text},
                        {"City", type text},
                        {"State", type text},
                        {"Postal Code", Int64.Type},
                        {"Region", type text},
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number}
                    })
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            formatString: 0
            lineageTag: c8b52fac-4a94-7d48-4676-8686fd6e4d00
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            lineageTag: 85844ea7-0051-c1b2-f04b-5616e93345cb
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 97ac53ec-6a2e-4553-70ea-8e5f4b1873d4
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: ee0fa07f-a296-dfe4-f75b-4c661aa3b581
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            lineageTag: 32dac3cb-fb4a-b334-44a4-b1de812f2f91
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            lineageTag: 7135dc8d-bd23-8aba-9e69-a6a98825fbaa
            summarizeBy: none
            sourceColumn: Customer ID

        column 'Segment'
            dataType: string
            lineageTag: 9adf2659-1a54-7cd5-efbf-460e4be62ac6
            summarizeBy: none
            sourceColumn: Segment

        column 'Country'
            dataType: string
            lineageTag: 12902d21-a1c0-f615-f8f7-c469576cb536
            summarizeBy: none
            sourceColumn: Country

        column 'City'
            dataType: string
            lineageTag: ed521c5d-adab-0a0e-e6af-3ecd20223646
            summarizeBy: none
            sourceColumn: City

        column 'State'
            dataType: string
            lineageTag: c4d20697-8abb-1b61-4881-4cd040e1a6cc
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            formatString: 0
            lineageTag: 2815e28d-c254-665a-46bf-b1161eeca770
            summarizeBy: none
            sourceColumn: Postal Code

        column 'Region'
            dataType: string
            lineageTag: 2ba2df33-d6c1-8923-b03d-411218715e71
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            lineageTag: 6d54cb68-cae5-f676-eaee-6f9bef1605bb
            summarizeBy: none
            sourceColumn: Product ID

        column 'Category'
            dataType: string
            lineageTag: 6bfc01d9-b5de-7842-e6b3-b2705ee82d4c
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: 35a5f08c-f987-6e6b-30dd-6cc7dff79e4a
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: 1a5a6467-85b7-5c4e-52d6-36df3e90c794
            summarizeBy: none
            sourceColumn: Product Name

        column 'Sales'
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: a1da1cbb-ec5b-bfc2-cbfc-7be59e12f283
            summarizeBy: sum
            sourceColumn: Sales

        column 'Quantity'
            dataType: int64
            formatString: 0
            lineageTag: 6dba02cd-6253-fe71-dbee-fc113d969dbf
            summarizeBy: sum
            sourceColumn: Quantity

        column 'Discount'
            dataType: double
            formatString: 0.00%
            lineageTag: 2d6122d7-2903-544b-3a61-6971015219c9
            summarizeBy: average
            sourceColumn: Discount

        column 'Profit'
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: 6bf25413-b0fa-27cf-9252-b1d63ff0880b
            summarizeBy: sum
            sourceColumn: Profit

        // --- ALL DAX MEASURES ---

        measure 'Category (Short)' =
            // Original Tableau: [Category]
            // DAX equivalent (manual review recommended)
            SUM(Orders[Sales])
            lineageTag: d6e091e6-aa0f-93f9-9eac-28ec0102313b

        measure 'Logic 400' =
            // Original Tableau: [Sales] < 400
            // DAX equivalent (manual review recommended)
            SUM(Orders[Sales])
            lineageTag: 3639500c-05a9-1e04-f74f-be999bbd7703

        measure 'Country (Short)' =
            // Original Tableau: [Country]
            // DAX equivalent (manual review recommended)
            SUM(Orders[Sales])
            lineageTag: 9cc25652-5ae2-cd61-c321-c65eda88d1af

    // ===========================================
    // DIMENSION TABLE: Customers
    // ===========================================

    table Customers
        lineageTag: 98955eb9-4810-5fbd-ca18-7a7ba1d480fe

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Customer ID", type text},
                        {"Customer Name", type text}
                    })
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            lineageTag: b7259c7a-a066-a590-01ae-4f662bce05c5
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            lineageTag: 13da3821-5662-5abd-233b-28e72eaa35c4
            summarizeBy: none
            sourceColumn: Customer Name

    // ===========================================
    // DIMENSION TABLE: Products
    // ===========================================

    table Products
        lineageTag: 6c0e601b-9ea9-10b9-05c2-249c1f1f6c15

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text}
                    })
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            lineageTag: 07f50882-238a-cec7-1fa0-77f916c8ed5d
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            lineageTag: 4bdf9b27-a74a-d752-8cb2-a1d85ac9af93
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: 7d2914d7-3c76-3e4c-9512-63a2aa579afd
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: d547834b-19dd-b6e1-ebe5-b867e4ce0ec7
            summarizeBy: none
            sourceColumn: Product Name

    // ===========================================
    // DATE TABLE (DAX-generated)
    // ===========================================

    table 'Date'
        lineageTag: 4d1da033-eec5-77cc-4fe7-52d0e1368a7c
        dataCategory: Time

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 4bf28e75-2827-a4f6-74de-a57742da3e75
            summarizeBy: none
            isKey: true
            isNameInferred: true
            expression: CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Year
            dataType: int64
            formatString: 0
            lineageTag: 85547848-e718-2c3b-8b21-bfe7347d9218
            summarizeBy: none
            expression: YEAR('Date'[Date])

        column Month
            dataType: int64
            formatString: 0
            lineageTag: 30b5c5dd-b386-1c85-6037-9d92f918f81f
            summarizeBy: none
            expression: MONTH('Date'[Date])

        column 'Month Name'
            dataType: string
            lineageTag: 8bfbbb5a-1f08-d0c3-216b-c49b57cd2d88
            summarizeBy: none
            expression: FORMAT('Date'[Date], "MMMM")

        column Quarter
            dataType: string
            lineageTag: 567551fc-f996-d4cb-9090-0499efbdb2c7
            summarizeBy: none
            expression: "Q" & FORMAT(QUARTER('Date'[Date]), "0")

    // ===========================================
    // RELATIONSHIPS
    // ===========================================

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: 'Date'
        toColumn: Date
