table Location
	lineageTag: 138a1cce-eb65-5ae7-ae7f-aa4f76f60203

	column 'Postal Code'
		dataType: string
		lineageTag: dccc864d-f191-532b-be51-d4de66369aa0
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 60c2389a-bde8-5037-b933-58f20d192aaa
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 1defc8a8-e42f-5cb9-9754-0a170fa84684
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 31b5772f-2759-52c2-90f1-e43e9e453543
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Country/Region'
		dataType: string
		lineageTag: eb3579a8-bfff-5ee4-849d-90a3ea810600
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	partition Location = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Location.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromoteHeaders, {{"Postal Code", type text}, {"City", type text}, {"State", type text}, {"Region", type text}, {"Country/Region", type text}}, "en-US")
				in
				    ChangedType
