table Orders
	lineageTag: e527cf94-2b24-5a55-b569-71ecdb4650ae

	column 'Row ID'
		dataType: string
		lineageTag: 8b82776a-8455-596d-857d-cc5422174f04
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 84b4120d-abca-5179-83ff-0d8e7dc06f9f
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: string
		lineageTag: e782a444-b313-5075-985f-68135c63f66d
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: string
		lineageTag: 99301465-b929-5a68-a862-9bd4d303aa75
		summarizeBy: none
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 4efbf39c-bbc0-50df-aa8a-e0fcd14898b1
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 39f10f62-fc91-5209-8f10-9db46c1621ad
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 8ea79706-3201-56de-942c-3b15ba1398e2
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 2f570d57-0064-59f4-8503-e1f58377d370
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 5e2298a6-3924-5828-932b-ba3115b9e76a
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: string
		lineageTag: f4450022-6f87-5d22-91bc-e83d24596708
		summarizeBy: none
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: string
		lineageTag: 907a3fcb-6ee5-5627-9309-14d3c4ce1807
		summarizeBy: none
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: string
		lineageTag: a9dd3a9b-c5c7-583f-8cc3-2c2cc5e88657
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: string
		lineageTag: 9d82e03c-fac7-5164-ba16-a72f39553a3b
		summarizeBy: none
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Order Date (Year)' = YEAR('Orders'[Order Date])		dataType: int64		formatString: 0		lineageTag: 10e6da57-e723-50b2-87b1-2ce2611be0c2		summarizeBy: sum		annotation SummarizationSetBy = Automatic	measure '% Diff Orders' = DIVIDE((COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Order ID]))), NOT ISBLANK([__v]))) - COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Order ID]))), NOT ISBLANK([__v])))), COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Order ID]))), NOT ISBLANK([__v]))))		formatString: 0.0%;-0.0%;-		displayFolder: Tableau calcs		lineageTag: b0a34fe0-24d9-5393-b70a-31b662201508	measure '% Diff Customers' = DIVIDE((COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Customer ID]))), NOT ISBLANK([__v]))) - COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Customer ID]))), NOT ISBLANK([__v])))), COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Customer ID]))), NOT ISBLANK([__v]))))		formatString: 0.0%;-0.0%;-		displayFolder: Tableau calcs		lineageTag: 86a99b46-fc3e-5cbb-88bd-ce436ada9939	measure '% Diff Quantity' = DIVIDE((SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Quantity])) - SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Quantity]))), SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Quantity])))		formatString: 0.0%;-0.0%;-		displayFolder: Tableau calcs		lineageTag: fb2b81b1-09aa-599c-9b29-5687dff2faad	measure '% Diff Profit' = DIVIDE((SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Profit])) - SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Profit]))), SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Profit])))		formatString: 0.0%;-0.0%;-		displayFolder: Tableau calcs		lineageTag: 98fe6988-627e-5fa5-8523-841030d09bbc	measure '% Diff Sales per Customers' = DIVIDE(([CY Sales per Customer] - [PY Sales per Customer]), [PY Sales per Customer])		formatString: 0.0%;-0.0%;-		displayFolder: Tableau calcs		lineageTag: 8fc604a5-2230-562f-b25d-4d229f526ab3	measure 'CY Sales per Customer' = DIVIDE(SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Sales])), COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Customer ID]))), NOT ISBLANK([__v]))))		formatString: "$"#,##0;-"$"#,##0		displayFolder: Tableau calcs		lineageTag: 4e849ab1-f223-5053-a0d7-3073e1fb258d	measure 'PY Sales per Customer' = DIVIDE(SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Sales])), COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Customer ID]))), NOT ISBLANK([__v]))))		formatString: "$"#,##0;-"$"#,##0		displayFolder: Tableau calcs		lineageTag: 6c48f65e-771f-551f-ade0-11f905dc2126	measure 'KPI CY Less PY' = IF((SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Sales])) < SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Sales]))), "⬤", "")		formatString: #,##0.00		displayFolder: Tableau calcs		lineageTag: 36514fb1-3e18-5cd1-99c5-0d826b3aa91c	measure '% Diff Sales' = DIVIDE((SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Sales])) - SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Sales]))), SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Sales])))		formatString: 0.0%;-0.0%;-		displayFolder: Tableau calcs		lineageTag: 4e1cf8fa-9d6f-5dae-a297-b345d4f011bd	measure '{SUM([CY Sales])}' = CALCULATE(SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Sales])), REMOVEFILTERS())		formatString: #,##0.00		displayFolder: Tableau calcs		lineageTag: 8ece90ed-9ed5-564b-8252-8c918ae3cc84	measure 'CNTD CY Customers' = COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Customer ID]))), NOT ISBLANK([__v])))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: e3434abe-87ad-52c5-9e9e-0300323e1015	measure 'MIN Order Date' = MIN('Orders'[Order Date])		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: 24f2bd11-f866-5e0a-857b-f4b57ac9e419	measure 'CNTD PY Customers' = COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Customer ID]))), NOT ISBLANK([__v])))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: c1344d11-89e5-5eb9-a5d5-eee3e8f63913	measure 'CNTD CY Orders' = COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Order ID]))), NOT ISBLANK([__v])))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: 5e4ec212-78e1-5b5e-b5d5-4cf76d95fcb9	measure 'CNTD PY Orders' = COUNTROWS(FILTER(DISTINCT(SELECTCOLUMNS('Orders', "__v", IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Order ID]))), NOT ISBLANK([__v])))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: bec0e475-3c96-551a-b5b2-8bb50638b046	measure 'CY Profit' = SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Profit]))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: 646fa285-83ad-57c0-baab-a5564a8e5475	measure 'PY Profit' = SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Profit]))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: e5ca4ed7-b51c-5825-aa44-c59ddb4cb50a	measure 'CY Quantity' = SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Quantity]))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: 676dfb08-d455-5838-97e8-b01fb69393c5	measure 'PY Quantity' = SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Quantity]))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: a0efa08e-bd61-5276-bb81-c0c5ccd17ba8	measure 'CY Sales' = SUMX('Orders', IF((YEAR('Orders'[Order Date]) = SELECTEDVALUE('Select Year'[Select Year], 2023)), 'Orders'[Sales]))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: 4321fefe-347b-5e34-88e3-c32eb29afca8	measure 'PY Sales' = SUMX('Orders', IF((YEAR('Orders'[Order Date]) = (SELECTEDVALUE('Select Year'[Select Year], 2023) - 1)), 'Orders'[Sales]))		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: acd0436d-7be0-54b9-9cda-8f083d333705	measure 'MAX Order Date' = MAX('Orders'[Order Date])		formatString: #,##0.00		displayFolder: Auto measures		lineageTag: a7f97df2-c16b-5662-adf7-9126d573247e	partition Orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Orders.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromoteHeaders, {{"Row ID", type text}, {"Order ID", type text}, {"Order Date", type text}, {"Ship Date", type text}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Segment", type text}, {"Postal Code", type text}, {"Product ID", type text}, {"Sales", type text}, {"Quantity", type text}, {"Discount", type text}, {"Profit", type text}}, "en-US")
				in
				    ChangedType
