// =============================================
// SECTION 12 -- LOD EXPRESSIONS -- DAX MEASURES
// Converted from Tableau calculated fields
// Source: tableau-source/course/tableau-files/Section 12 - LOD Expressions/extracted/LOD Expressions.twb
// TWB datasources: "Small Data Source" (federated.0mnok8g1jr2xrc1d2pdje1l9u16p),
//                  "Big Data Source" (federated.1hpyone17bxgk51b0kg750hoe27w)
// =============================================

// -----------------------------------------------
// CALCULATED FIELDS / MEASURES
// -----------------------------------------------

// Tableau: { FIXED [Category] : SUM([Sales]) }
// LOD FIXED -- calculates SUM of Sales for each Category regardless of other filters
Sales By Category =
    CALCULATE(
        SUM(Orders[Sales]),
        ALLEXCEPT(Orders, Orders[Category])
    )

// Tableau: { EXCLUDE [Category] : SUM([Sales]) }
// LOD EXCLUDE -- calculates SUM of Sales excluding Category from the granularity
Sales Exclude Category =
    CALCULATE(
        SUM(Orders[Sales]),
        ALL(Orders[Category])
    )

// Tableau: { INCLUDE [First_Name] : SUM([Sales]) }
// LOD INCLUDE -- adds First_Name to the granularity for SUM of Sales
Calculation1 =
    CALCULATE(
        SUM(Orders[Sales]),
        VALUES(Customers[Customer Name])
    )

// Tableau: { INCLUDE [First_Name] : SUM([Sales]) }
// LOD INCLUDE -- same as Calculation1, used for average computation
Avg Sales of Customers =
    CALCULATE(
        SUM(Orders[Sales]),
        VALUES(Customers[Customer Name])
    )

// Tableau: { FIXED [Customer_ID]: COUNT([Order_ID]) }
// LOD FIXED -- counts orders per customer regardless of other filters
Nr. of Orders per Customer =
    CALCULATE(
        COUNT(Orders[Order ID]),
        ALLEXCEPT(Orders, Orders[Customer ID])
    )

// Tableau: IF [Sub_Category] = "Tables" THEN [Sales] END
// Row-level calculation -- returns Sales only for the "Tables" sub-category
Sales of Tables =
    CALCULATE(
        SUM(Orders[Sales]),
        Orders[Sub-Category] = "Tables"
    )

// Tableau: { EXCLUDE [Sub_Category]: SUM([Calculation_1596526105595723802]) }
// LOD EXCLUDE -- references "Sales of Tables" (internal name Calculation_1596526105595723802)
// Excludes Sub-Category from granularity when summing Sales of Tables
Exclude Sub Category =
    CALCULATE(
        [Sales of Tables],
        ALL(Orders[Sub-Category])
    )

// Tableau: SUM([Sales]) - SUM([Calculation_1596526105598066726])
// References "Exclude Sub Category" (internal name Calculation_1596526105598066726)
Difference =
    SUM(Orders[Sales]) - [Exclude Sub Category]
