// =============================================
// SECTION 11 -- ACTIONS -- TMDL MODEL
// Tabular Model Definition Language
// Source: tableau-source/course/tableau-files/Section 11 - Actions/extracted/Section 11 - Tableau Actions.twb
// TWB datasources: "Small Data Source" (federated.0uo54ao1ji2f2j1ewx8350q74y73)
//                  "Big Data Source" (federated.18qfvdle0xzwb917bq3ba0fmivoj)
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    // ===========================================
    // FACT TABLE: Orders
    // TWB: Orders.csv + Orders_Archive.csv (union)
    // ===========================================

    table Orders

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Row ID", Int64.Type},
                        {"Order ID", type text},
                        {"Order Date", type date},
                        {"Ship Date", type date},
                        {"Ship Mode", type text},
                        {"Customer ID", type text},
                        {"Segment", type text},
                        {"Country", type text},
                        {"City", type text},
                        {"State", type text},
                        {"Postal Code", Int64.Type},
                        {"Region", type text},
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number}
                    })
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            formatString: 0
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer ID

        column Segment
            dataType: string
            summarizeBy: none
            sourceColumn: Segment

        column Country
            dataType: string
            summarizeBy: none
            sourceColumn: Country

        column City
            dataType: string
            summarizeBy: none
            sourceColumn: City

        column State
            dataType: string
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            formatString: 0
            summarizeBy: none
            sourceColumn: Postal Code

        column Region
            dataType: string
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Product ID

        column Category
            dataType: string
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Product Name

        column Sales
            dataType: double
            formatString: $#,0.00;($#,0.00);$#,0.00
            summarizeBy: sum
            sourceColumn: Sales

        column Quantity
            dataType: int64
            formatString: 0
            summarizeBy: sum
            sourceColumn: Quantity

        column Discount
            dataType: double
            formatString: 0.00%
            summarizeBy: average
            sourceColumn: Discount

        column Profit
            dataType: double
            formatString: $#,0.00;($#,0.00);$#,0.00
            summarizeBy: sum
            sourceColumn: Profit

        // --- MEASURES ---

        measure 'Total Value' =
            // Tableau Parameter: Total (real, default=0, format=C1033%)
            SELECTEDVALUE('Total Parameter'[Total], 0)

        measure Calculation1 =
            // Original Tableau: [Parameters].[Parameter 1]
            [Total Value]

        measure 'Total Big DS' =
            // Original Tableau: [Parameters].[Parameter 1] (Big Data Source)
            [Total Value]

        measure 'Sales Bin' =
            // Original Tableau: [Sales] (bin field)
            FLOOR(Orders[Sales], 100)

        measure 'Score Bin' =
            // Original Tableau: [Score] (bin field)
            FLOOR(Orders[Score], 10)

        measure 'Sub-Category URL' =
            // Tableau URL Action: https://en.wikipedia.org/wiki/<[Sub_Category]>
            "https://en.wikipedia.org/wiki/" & SELECTEDVALUE(Orders[Sub-Category])

    // ===========================================
    // DIMENSION TABLE: Customers
    // ===========================================

    table Customers

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Customer ID", type text},
                        {"Customer Name", type text}
                    })
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Customer Name

    // ===========================================
    // DIMENSION TABLE: Products
    // ===========================================

    table Products

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text}
                    })
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            summarizeBy: none
            sourceColumn: Product Name

    // ===========================================
    // WHAT-IF PARAMETER TABLE: Total Parameter
    // Tableau Parameter: Total (real, default=0, format=C1033%)
    // ===========================================

    table 'Total Parameter'

        column Total
            dataType: double
            formatString: $#,0.00
            summarizeBy: none
            isKey: true
            expression: GENERATESERIES(0, 10000, 100)

    // ===========================================
    // DATE TABLE (DAX-generated)
    // ===========================================

    table 'Date'
        dataCategory: Time

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            summarizeBy: none
            isKey: true
            isNameInferred: true
            expression: CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Year
            dataType: int64
            formatString: 0
            summarizeBy: none
            expression: YEAR('Date'[Date])

        column Month
            dataType: int64
            formatString: 0
            summarizeBy: none
            expression: MONTH('Date'[Date])

        column 'Month Name'
            dataType: string
            summarizeBy: none
            expression: FORMAT('Date'[Date], "MMMM")

        column Quarter
            dataType: string
            summarizeBy: none
            expression: "Q" & FORMAT(QUARTER('Date'[Date]), "0")

    // ===========================================
    // RELATIONSHIPS
    // ===========================================

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: 'Date'
        toColumn: Date
