// =============================================
// SECTION 06 — METADATA — TMDL MODEL
// Tabular Model Definition Language
// Source: tableau-source/course/tableau-files/Section 06 - Metadata/extracted/Section 6 - Data Modelling.twb
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    // ===========================================
    // FACT TABLE: Orders
    // ===========================================

    table Orders
        lineageTag: 51b42eb0-c392-4709-aa31-ecd2ebea973b

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Row ID", Int64.Type}},
                        {{"Order ID", type text}},
                        {{"Order Date", type date}},
                        {{"Ship Date", type date}},
                        {{"Ship Mode", type text}},
                        {{"Customer ID", type text}},
                        {{"Segment", type text}},
                        {{"Country", type text}},
                        {{"City", type text}},
                        {{"State", type text}},
                        {{"Postal Code", Int64.Type}},
                        {{"Region", type text}},
                        {{"Product ID", type text}},
                        {{"Category", type text}},
                        {{"Sub-Category", type text}},
                        {{"Product Name", type text}},
                        {{"Sales", type number}},
                        {{"Quantity", Int64.Type}},
                        {{"Discount", type number}},
                        {{"Profit", type number}}
                    }})
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            formatString: 0
            lineageTag: 5512e2ea-d4f0-4a6c-b58d-d8021da3e709
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            lineageTag: b42b206a-43a0-40f3-9a5e-32d7f4fe1741
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 8f34c687-f236-46c6-be7c-7c4d37a2cc1c
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 73c3e65b-1fc3-4098-a7c7-3cc51cca2108
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            lineageTag: 7c930643-774f-4c8a-8def-8e1e0d06692f
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            lineageTag: 304c7c2f-6623-4a8f-8be1-74ffe1796945
            summarizeBy: none
            sourceColumn: Customer ID

        column Segment
            dataType: string
            lineageTag: a8dae796-03b2-4fea-97d4-c748051c3bda
            summarizeBy: none
            sourceColumn: Segment

        column Country
            dataType: string
            lineageTag: b68d8d72-30d4-4ac2-ad3f-f7ede4b74d21
            summarizeBy: none
            sourceColumn: Country

        column City
            dataType: string
            lineageTag: 255cb3e3-05ba-42ae-80e5-cdc0ee690bf5
            summarizeBy: none
            sourceColumn: City

        column State
            dataType: string
            lineageTag: 5d9109f1-faea-4ea6-8736-dd247bbd8ce2
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            formatString: 0
            lineageTag: 96e18b69-e33e-416b-b560-1aaf34551cfc
            summarizeBy: none
            sourceColumn: Postal Code

        column Region
            dataType: string
            lineageTag: 26453e31-25a6-43c5-9959-fd6a8a5aae6c
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            lineageTag: dcf6a385-1fa6-45ec-b7eb-3571f7f9dd16
            summarizeBy: none
            sourceColumn: Product ID

        column Category
            dataType: string
            lineageTag: 40a8938a-38a3-4f4c-9c7a-29f2a754b9e8
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: 6c331259-1c24-4f72-90f0-3a6c94692b7d
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: 28aedf41-b447-4077-b31a-7262ee70c47b
            summarizeBy: none
            sourceColumn: Product Name

        column Sales
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: 21d2018e-bccb-4788-ad6f-01b0d1380aeb
            summarizeBy: sum
            sourceColumn: Sales

        column Quantity
            dataType: int64
            formatString: 0
            lineageTag: b2cd9740-d608-48d8-acaf-e3c13bd6e90c
            summarizeBy: sum
            sourceColumn: Quantity

        column Discount
            dataType: double
            formatString: 0.00%
            lineageTag: 3b5873c4-11f2-48ab-ae36-5a8c8ab0ad7a
            summarizeBy: average
            sourceColumn: Discount

        column Profit
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: 1efd0651-2cd7-4c95-916b-0298437292d5
            summarizeBy: sum
            sourceColumn: Profit

        // --- Calculated Column: Logic 400 ---
        // Tableau: [Sales] < 400 (boolean)
        column 'Logic 400'
            dataType: boolean
            lineageTag: 6f9055a1-2399-40ee-a12a-1d4424455288
            summarizeBy: none
            isDataTypeInferred: true
            expression: IF(Orders[Sales] < 400, TRUE(), FALSE())

    // ===========================================
    // DIMENSION TABLE: Customers
    // ===========================================

    table Customers
        lineageTag: 58f75b78-3d8f-4d69-a43d-c4991fbd3a93

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Customer ID", type text}},
                        {{"Customer Name", type text}}
                    }})
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            lineageTag: 35bce179-af45-4f2f-9c9b-8384e427b5fa
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            lineageTag: 059f0325-8482-44ba-b8e1-d8c2520d8b67
            summarizeBy: none
            sourceColumn: Customer Name

    // ===========================================
    // DIMENSION TABLE: Products
    // ===========================================

    table Products
        lineageTag: ce2645ab-8e3a-4aad-a315-9e4aa7a70a04

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Product ID", type text}},
                        {{"Category", type text}},
                        {{"Sub-Category", type text}},
                        {{"Product Name", type text}}
                    }})
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            lineageTag: 378a135c-b0d7-44b5-b73e-6dc0143453bd
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            lineageTag: 23281d8f-f0d0-47ad-90e0-3cfffabe6f74
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: 40b76262-df13-41d4-aa05-1e4e2288f20a
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: ff8209f4-3bc1-43ad-8af7-fb984076d204
            summarizeBy: none
            sourceColumn: Product Name

    // ===========================================
    // DATE TABLE (DAX-generated calendar)
    // ===========================================

    table Date
        lineageTag: c911c487-2d18-4671-9f57-a185643605bd

        partition Date = calculated
            mode: import
            source = CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 8c7bb884-6e53-4b9f-8b49-0296b88f90ff
            summarizeBy: none
            isKey: true

        column Year
            dataType: int64
            formatString: 0
            lineageTag: 76064314-97f2-4a48-8fa1-9a09e04e0d33
            summarizeBy: none
            isDataTypeInferred: true
            expression: YEAR([Date])

        column Month
            dataType: int64
            formatString: 0
            lineageTag: 161f4a1d-64b1-4598-9fbd-3b9388f6e390
            summarizeBy: none
            isDataTypeInferred: true
            expression: MONTH([Date])

        column 'Month Name'
            dataType: string
            lineageTag: 57fa9dd4-c0fa-437c-91ca-b2d546a243bf
            summarizeBy: none
            isDataTypeInferred: true
            expression: FORMAT([Date], "MMMM")

        column Quarter
            dataType: string
            lineageTag: e3eb2bf2-1aa0-4131-8392-5bebf3456ff4
            summarizeBy: none
            isDataTypeInferred: true
            expression: "Q" & FORMAT([Date], "Q")

    // ===========================================
    // RELATIONSHIPS
    // ===========================================

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: singleDirection

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: singleDirection

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: Date
        toColumn: Date
        crossFilteringBehavior: singleDirection
