// =============================================================
// SECTION 12 — TABLE CALCULATIONS — DAX MEASURES
// Converted from Tableau calculated fields
// Source: Section 12 - Table Calculations.twb
// Data Sources: Small Data Source (Orders+Customers+Products),
//               Big Data Source (Orders+Customers+Products)
// =============================================================

// -----------------------------------------------
// SMALL DATA SOURCE CALCULATIONS
// -----------------------------------------------

// #1 — Tableau: ZN(SUM([Sales])) - LOOKUP(ZN(SUM([Sales])), -1)
// Period-over-period difference in Sales
Calculation1 (Period Diff) =
    VAR CurrentSales = SUM(Orders[Sales])
    VAR PrevSales =
        CALCULATE(
            SUM(Orders[Sales]),
            OFFSET(-1, ALLSELECTED(Orders[Order Date]), ORDERBY(Orders[Order Date], ASC))
        )
    RETURN
        IF(ISBLANK(PrevSales), CurrentSales, CurrentSales - PrevSales)

// #2 — Tableau: RUNNING_SUM(SUM([Sales]))
// Running total of Sales
Calculation2 (Running Sum) =
    VAR CurrentDate = MAX(Orders[Order Date])
    RETURN
        CALCULATE(
            SUM(Orders[Sales]),
            FILTER(ALL(Orders[Order Date]), Orders[Order Date] <= CurrentDate)
        )

// #3 — Tableau: RANK_PERCENTILE(SUM([Sales]))
// Percentile rank of Sales
Calculation3 (Rank Percentile) =
    VAR CurrentSales = SUM(Orders[Sales])
    VAR AllSales = ADDCOLUMNS(ALLSELECTED(Orders[Order Date]), "@Sales", CALCULATE(SUM(Orders[Sales])))
    VAR CountBelow = COUNTROWS(FILTER(AllSales, [@Sales] < CurrentSales))
    VAR TotalCount = COUNTROWS(AllSales)
    RETURN
        DIVIDE(CountBelow, TotalCount - 1)

// #4 — Tableau: ZN(SUM([Sales])) - LOOKUP(ZN(SUM([Sales])), -1)
// Same as Calculation1 (duplicate in source .twb)
Calculation4 (Period Diff 2) =
    VAR CurrentSales = SUM(Orders[Sales])
    VAR PrevSales =
        CALCULATE(
            SUM(Orders[Sales]),
            OFFSET(-1, ALLSELECTED(Orders[Order Date]), ORDERBY(Orders[Order Date], ASC))
        )
    RETURN
        IF(ISBLANK(PrevSales), CurrentSales, CurrentSales - PrevSales)

// -----------------------------------------------
// BIG DATA SOURCE CALCULATIONS
// -----------------------------------------------

// #5 — Tableau: (ZN(SUM([Sales])) - LOOKUP(ZN(SUM([Sales])), -1)) / ABS(LOOKUP(ZN(SUM([Sales])), -1))
// Percentage change from previous period
Calculation1_1 (Pct Change) =
    VAR CurrentSales = SUM(Orders[Sales])
    VAR PrevSales =
        CALCULATE(
            SUM(Orders[Sales]),
            OFFSET(-1, ALLSELECTED(Orders[Order Date]), ORDERBY(Orders[Order Date], ASC))
        )
    RETURN
        IF(
            ISBLANK(PrevSales) || PrevSales = 0,
            BLANK(),
            DIVIDE(CurrentSales - PrevSales, ABS(PrevSales))
        )

// #6 — Tableau: RUNNING_SUM(SUM([Sales]))
// Running sum (Big Data Source)
Calculation1_Big (Running Sum) =
    VAR CurrentDate = MAX(Orders[Order Date])
    RETURN
        CALCULATE(
            SUM(Orders[Sales]),
            FILTER(ALL(Orders[Order Date]), Orders[Order Date] <= CurrentDate)
        )

// #7 — Tableau: LAST()
// Position from end of partition
Calculation2_Last =
    VAR TotalRows = COUNTROWS(ALLSELECTED(Orders[Sub-Category]))
    VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)
    RETURN
        TotalRows - CurrentRank

// #8 — Tableau: LOOKUP(SUM([Sales]), 2)
// Look ahead 2 positions
Lookup_Sales =
    CALCULATE(
        SUM(Orders[Sales]),
        OFFSET(2, ALLSELECTED(Orders[Sub-Category]), ORDERBY(SUM(Orders[Sales]), DESC))
    )

// #9 — Tableau: IF FIRST() = 0 THEN SUM([Sales]) END
// Show Sales only for first row in partition
First_Sales =
    VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)
    RETURN
        IF(CurrentRank = 1, SUM(Orders[Sales]), BLANK())

// #10 — Tableau: RANK(SUM([Sales]))
// Rank by Sales descending
Rank_Sales =
    RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, DESC, Dense)

// #11 — Tableau: LAST()
// Position from end (duplicate)
Last_Pos =
    VAR TotalRows = COUNTROWS(ALLSELECTED(Orders[Sub-Category]))
    VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)
    RETURN
        TotalRows - CurrentRank

// #12 — Tableau: FIRST()
// Position from start (0-based)
First_Pos =
    RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense) - 1

// #13 — Tableau: INDEX()
// 1-based index in partition
Index_Pos =
    RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)

// #14 — Tableau: RUNNING_SUM(SUM([Sales]))
// Running sum by Sub-Category
Running_Sales =
    VAR CurrentVal = SUM(Orders[Sales])
    VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)
    RETURN
        SUMX(
            FILTER(
                ADDCOLUMNS(
                    ALLSELECTED(Orders[Sub-Category]),
                    "@Sales", CALCULATE(SUM(Orders[Sales])),
                    "@Rank", RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)
                ),
                [@Rank] <= CurrentRank
            ),
            [@Sales]
        )
