// TMDL Semantic Model — Section 12: Table Calculations
// Generated from .twb XML source

model Model
    culture: en-US

    table Orders
        lineageTag: orders-table-calcs
        dataCategory: Regular

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Order_ID", type text},
                        {"Customer_ID", type text},
                        {"Product_ID", type text},
                        {"Order_Date", type date},
                        {"Shipping_Date", type date},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number},
                        {"Unit_Price", type number}
                    })
                in
                    ChangedTypes

        column 'Order ID' = Orders[Order_ID]
            dataType: string
        column 'Customer ID' = Orders[Customer_ID]
            dataType: string
        column 'Product ID' = Orders[Product_ID]
            dataType: string
        column 'Order Date' = Orders[Order_Date]
            dataType: dateTime
            formatString: dd/MM/yyyy
        column 'Ship Date' = Orders[Shipping_Date]
            dataType: dateTime
            formatString: dd/MM/yyyy
        column Sales
            dataType: decimal
            formatString: #,##0.00
        column Quantity
            dataType: int64
        column Discount
            dataType: decimal
        column Profit
            dataType: decimal
            formatString: #,##0.00
        column 'Unit Price' = Orders[Unit_Price]
            dataType: decimal
        column 'Sub-Category'
            dataType: string
            description: From Products join — used for table calc partitioning
        column Category
            dataType: string
        column 'Product Name'
            dataType: string
        column Country
            dataType: string
        column Region
            dataType: string

        // Small Data Source measures
        measure 'Calculation1 (Period Diff)' = VAR CurrentSales = SUM(Orders[Sales]) VAR PrevSales = CALCULATE(SUM(Orders[Sales]), OFFSET(-1, ALLSELECTED(Orders[Order Date]), ORDERBY(Orders[Order Date], ASC))) RETURN IF(ISBLANK(PrevSales), CurrentSales, CurrentSales - PrevSales)
        measure 'Calculation2 (Running Sum)' = VAR CurrentDate = MAX(Orders[Order Date]) RETURN CALCULATE(SUM(Orders[Sales]), FILTER(ALL(Orders[Order Date]), Orders[Order Date] <= CurrentDate))
        measure 'Calculation3 (Rank Percentile)' = VAR CurrentSales = SUM(Orders[Sales]) VAR AllSales = ADDCOLUMNS(ALLSELECTED(Orders[Order Date]), "@Sales", CALCULATE(SUM(Orders[Sales]))) VAR CountBelow = COUNTROWS(FILTER(AllSales, [@Sales] < CurrentSales)) VAR TotalCount = COUNTROWS(AllSales) RETURN DIVIDE(CountBelow, TotalCount - 1)
        measure 'Calculation4 (Period Diff 2)' = VAR CurrentSales = SUM(Orders[Sales]) VAR PrevSales = CALCULATE(SUM(Orders[Sales]), OFFSET(-1, ALLSELECTED(Orders[Order Date]), ORDERBY(Orders[Order Date], ASC))) RETURN IF(ISBLANK(PrevSales), CurrentSales, CurrentSales - PrevSales)

        // Big Data Source measures
        measure 'Calculation1_1 (Pct Change)' = VAR CurrentSales = SUM(Orders[Sales]) VAR PrevSales = CALCULATE(SUM(Orders[Sales]), OFFSET(-1, ALLSELECTED(Orders[Order Date]), ORDERBY(Orders[Order Date], ASC))) RETURN IF(ISBLANK(PrevSales) || PrevSales = 0, BLANK(), DIVIDE(CurrentSales - PrevSales, ABS(PrevSales)))
        measure 'Calculation1_Big (Running Sum)' = VAR CurrentDate = MAX(Orders[Order Date]) RETURN CALCULATE(SUM(Orders[Sales]), FILTER(ALL(Orders[Order Date]), Orders[Order Date] <= CurrentDate))
        measure Calculation2_Last = VAR TotalRows = COUNTROWS(ALLSELECTED(Orders[Sub-Category])) VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense) RETURN TotalRows - CurrentRank
        measure Lookup_Sales = CALCULATE(SUM(Orders[Sales]), OFFSET(2, ALLSELECTED(Orders[Sub-Category]), ORDERBY(SUM(Orders[Sales]), DESC)))
        measure First_Sales = VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense) RETURN IF(CurrentRank = 1, SUM(Orders[Sales]), BLANK())
        measure Rank_Sales = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, DESC, Dense)
        measure Last_Pos = VAR TotalRows = COUNTROWS(ALLSELECTED(Orders[Sub-Category])) VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense) RETURN TotalRows - CurrentRank
        measure First_Pos = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense) - 1
        measure Index_Pos = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)
        measure Running_Sales = VAR CurrentRank = RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense) RETURN SUMX(FILTER(ADDCOLUMNS(ALLSELECTED(Orders[Sub-Category]), "@Sales", CALCULATE(SUM(Orders[Sales])), "@Rank", RANKX(ALLSELECTED(Orders[Sub-Category]), SUM(Orders[Sales]),, ASC, Dense)), [@Rank] <= CurrentRank), [@Sales])

    table Customers
        lineageTag: customers-table-calcs

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
                in
                    PromotedHeaders

        column 'Customer ID' = Customers[Customer_ID]
            dataType: string
        column 'First Name' = Customers[First_Name]
            dataType: string
        column 'Last Name' = Customers[Last_Name]
            dataType: string
        column Country
            dataType: string
        column Score
            dataType: int64

    table Products
        lineageTag: products-table-calcs

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
                in
                    PromotedHeaders

        column 'Product ID' = Products[Product_ID]
            dataType: string
        column 'Product Name' = Products[Product_Name]
            dataType: string
        column Category
            dataType: string
        column 'Sub-Category'
            dataType: string

    // Relationships
    relationship Orders_Customers = Orders[Customer ID] -> Customers[Customer ID]
        crossFilteringBehavior: singleDirection

    relationship Orders_Products = Orders[Product ID] -> Products[Product ID]
        crossFilteringBehavior: singleDirection
