// =============================================
// SECTION 10 -- PARAMETERS -- TMDL MODEL
// Tabular Model Definition Language
// Source: tableau-source/course/tableau-files/Section 10 - Parameters/extracted/Section 10 - Parameters.twb
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    // ===========================================
    // FACT TABLE: Orders
    // ===========================================

    table Orders
        lineageTag: s10-fact-0000
        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Row ID", Int64.Type},
                        {"Order ID", type text},
                        {"Order Date", type date},
                        {"Ship Date", type date},
                        {"Ship Mode", type text},
                        {"Customer ID", type text},
                        {"Segment", type text},
                        {"Country", type text},
                        {"City", type text},
                        {"State", type text},
                        {"Postal Code", Int64.Type},
                        {"Region", type text},
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number}
                    })
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            formatString: 0
            lineageTag: s10-0001
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            lineageTag: s10-0002
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: s10-0003
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: s10-0004
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            lineageTag: s10-0005
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            lineageTag: s10-0006
            summarizeBy: none
            sourceColumn: Customer ID

        column 'Segment'
            dataType: string
            lineageTag: s10-0007
            summarizeBy: none
            sourceColumn: Segment

        column 'Country'
            dataType: string
            lineageTag: s10-0008
            summarizeBy: none
            sourceColumn: Country

        column 'City'
            dataType: string
            lineageTag: s10-0009
            summarizeBy: none
            sourceColumn: City

        column 'State'
            dataType: string
            lineageTag: s10-0010
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            formatString: 0
            lineageTag: s10-0011
            summarizeBy: none
            sourceColumn: Postal Code

        column 'Region'
            dataType: string
            lineageTag: s10-0012
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            lineageTag: s10-0013
            summarizeBy: none
            sourceColumn: Product ID

        column 'Category'
            dataType: string
            lineageTag: s10-0014
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: s10-0015
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: s10-0016
            summarizeBy: none
            sourceColumn: Product Name

        column 'Sales'
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: s10-0017
            summarizeBy: sum
            sourceColumn: Sales

        column 'Quantity'
            dataType: int64
            formatString: 0
            lineageTag: s10-0018
            summarizeBy: sum
            sourceColumn: Quantity

        column 'Discount'
            dataType: double
            formatString: 0.00%
            lineageTag: s10-0019
            summarizeBy: average
            sourceColumn: Discount

        column 'Profit'
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: s10-0020
            summarizeBy: sum
            sourceColumn: Profit

        // --- DAX MEASURES (from TWB calculated fields and parameters) ---

        // Tableau: [Sales] < 400 (boolean)
        measure 'Logic 400' =
            IF(SUM(Orders[Sales]) < 400, TRUE(), FALSE())
            lineageTag: s10-m001

        // Tableau: [Country] aliases {"France"->"FR", "Germany"->"DE"}
        measure 'Country (Short)' =
            SWITCH(
                SELECTEDVALUE(Orders[Country]),
                "France", "FR",
                "Germany", "DE",
                SELECTEDVALUE(Orders[Country])
            )
            lineageTag: s10-m002

        // Tableau: If SUM([Profit]) < [Parameters].[Parameter 4] THEN 'Red' ELSE 'Green' END
        measure 'KPI Colors' =
            IF(SUM(Orders[Profit]) < [Choose Threshold Value], "Red", "Green")
            lineageTag: s10-m003

        // Tableau: CASE [Parameters].[Parameter 1] WHEN 'Country' THEN [Country] WHEN 'Category' THEN [Category] END
        measure 'Dynamic Dimension' =
            SWITCH(
                [Choose Dimension Value],
                "Country", SELECTEDVALUE(Orders[Country]),
                "Category", SELECTEDVALUE(Orders[Category]),
                SELECTEDVALUE(Orders[Country])
            )
            lineageTag: s10-m004

        // Tableau: CASE [Parameters].[Parameter 2] WHEN 'Sales' THEN [Sales] WHEN 'Profit' THEN [Profit] WHEN 'Quantity' THEN [Quantity] END
        measure 'Dynamic Measure' =
            SWITCH(
                [Choose Measure Value],
                "Sales", SUM(Orders[Sales]),
                "Profit", SUM(Orders[Profit]),
                "Quantity", SUM(Orders[Quantity]),
                SUM(Orders[Sales])
            )
            lineageTag: s10-m005

        // Tableau: [Category] aliases {"Furniture"->"F", "Office Supplies"->"O", "Technology"->"T"}
        measure 'Category (Short)' =
            SWITCH(
                SELECTEDVALUE(Orders[Category]),
                "Furniture", "F",
                "Office Supplies", "O",
                "Technology", "T",
                SELECTEDVALUE(Orders[Category])
            )
            lineageTag: s10-m006

        // Tableau: Sales (bin) -- dynamic bin using Choose Size of Bins parameter
        measure 'Sales (bin)' =
            INT(Orders[Sales] / [Choose Size of Bins Value]) * [Choose Size of Bins Value]
            lineageTag: s10-m007

        // Tableau: Score (bin) -- bin on [Score], class=bin, auto-sized
        measure 'Score (bin)' =
            INT(Orders[Score] / 10) * 10
            lineageTag: s10-m008

        // Top N filter using Choose Top N Products parameter
        measure 'Top N Filter Active' =
            VAR CurrentRank =
                RANKX(
                    ALLSELECTED(Orders[Product Name]),
                    [Dynamic Measure],
                    ,
                    DESC,
                    Dense
                )
            RETURN
                IF(CurrentRank <= [Choose Top N Products Value], 1, 0)
            lineageTag: s10-m009

    // ===========================================
    // PARAMETER TABLE: Choose Dimension (string, disconnected)
    // TWB: Parameter 1, members: "Country", "Category"
    // ===========================================

    table 'Choose Dimension'
        lineageTag: s10-pd01

        column 'Choose Dimension'
            dataType: string
            lineageTag: s10-pd02
            summarizeBy: none
            isKey: true

        measure 'Choose Dimension Value' =
            SELECTEDVALUE('Choose Dimension'[Choose Dimension], "Country")
            lineageTag: s10-pd03

    // ===========================================
    // PARAMETER TABLE: Choose Measure (string, disconnected)
    // TWB: Parameter 2, members: "Sales", "Profit", "Quantity"
    // ===========================================

    table 'Choose Measure'
        lineageTag: s10-pm01

        column 'Choose Measure'
            dataType: string
            lineageTag: s10-pm02
            summarizeBy: none
            isKey: true

        measure 'Choose Measure Value' =
            SELECTEDVALUE('Choose Measure'[Choose Measure], "Sales")
            lineageTag: s10-pm03

    // ===========================================
    // WHAT-IF PARAMETER: Choose Size of Bins
    // TWB: Parameter 3, real, range 5.0-25.0, step 5.0, default=20
    // ===========================================

    table 'Choose Size of Bins'
        lineageTag: s10-pb01

        column 'Choose Size of Bins'
            dataType: double
            lineageTag: s10-pb02
            summarizeBy: none
            isKey: true
            expression: GENERATESERIES(5.0, 25.0, 5.0)

        measure 'Choose Size of Bins Value' =
            SELECTEDVALUE('Choose Size of Bins'[Choose Size of Bins], 20)
            lineageTag: s10-pb03

    // ===========================================
    // WHAT-IF PARAMETER: Choose Threshold
    // TWB: Parameter 4, integer, default=10000
    // ===========================================

    table 'Choose Threshold'
        lineageTag: s10-pt01

        column 'Choose Threshold'
            dataType: int64
            lineageTag: s10-pt02
            summarizeBy: none
            isKey: true
            expression: GENERATESERIES(0, 50000, 1000)

        measure 'Choose Threshold Value' =
            SELECTEDVALUE('Choose Threshold'[Choose Threshold], 10000)
            lineageTag: s10-pt03

    // ===========================================
    // WHAT-IF PARAMETER: Choose Top N Products
    // TWB: Parameter 5, integer, range 0-50, step 5, default=15
    // ===========================================

    table 'Choose Top N Products'
        lineageTag: s10-pn01

        column 'Choose Top N Products'
            dataType: int64
            lineageTag: s10-pn02
            summarizeBy: none
            isKey: true
            expression: GENERATESERIES(0, 50, 5)

        measure 'Choose Top N Products Value' =
            SELECTEDVALUE('Choose Top N Products'[Choose Top N Products], 15)
            lineageTag: s10-pn03

    // ===========================================
    // DIMENSION TABLE: Customers
    // ===========================================

    table Customers
        lineageTag: s10-c001

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Customer ID", type text},
                        {"Customer Name", type text}
                    })
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            lineageTag: s10-c002
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            lineageTag: s10-c003
            summarizeBy: none
            sourceColumn: Customer Name

    // ===========================================
    // DIMENSION TABLE: Products
    // ===========================================

    table Products
        lineageTag: s10-p001

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Product ID", type text},
                        {"Category", type text},
                        {"Sub-Category", type text},
                        {"Product Name", type text}
                    })
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            lineageTag: s10-p002
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            lineageTag: s10-p003
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: s10-p004
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: s10-p005
            summarizeBy: none
            sourceColumn: Product Name

    // ===========================================
    // DATE TABLE (DAX-generated)
    // ===========================================

    table 'Date'
        lineageTag: s10-d001
        dataCategory: Time

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: s10-d002
            summarizeBy: none
            isKey: true
            isNameInferred: true
            expression: CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Year
            dataType: int64
            formatString: 0
            lineageTag: s10-d003
            summarizeBy: none
            expression: YEAR('Date'[Date])

        column Month
            dataType: int64
            formatString: 0
            lineageTag: s10-d004
            summarizeBy: none
            expression: MONTH('Date'[Date])

        column 'Month Name'
            dataType: string
            lineageTag: s10-d005
            summarizeBy: none
            expression: FORMAT('Date'[Date], "MMMM")

        column Quarter
            dataType: string
            lineageTag: s10-d006
            summarizeBy: none
            expression: "Q" & FORMAT(QUARTER('Date'[Date]), "0")

    // ===========================================
    // RELATIONSHIPS
    // ===========================================

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: bothDirections

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: 'Date'
        toColumn: Date
