// =============================================
// SECTION 05 — DATA SOURCES — TMDL MODEL
// Tabular Model Definition Language
// Source: tableau-source/course/tableau-files/Section 05 - Data Sources/extracted/Section 5 - Data Sources.twb
// =============================================

model Model
    culture: en-US
    defaultPowerBIDataSourceVersion: powerBI_V3
    discourageImplicitMeasures: true

    // ===========================================
    // FACT TABLE: Orders
    // ===========================================

    table Orders
        lineageTag: d6d32077-1ddb-476c-97bf-0eeafe07c98d

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Row ID", Int64.Type}},
                        {{"Order ID", type text}},
                        {{"Order Date", type date}},
                        {{"Ship Date", type date}},
                        {{"Ship Mode", type text}},
                        {{"Customer ID", type text}},
                        {{"Segment", type text}},
                        {{"Country", type text}},
                        {{"City", type text}},
                        {{"State", type text}},
                        {{"Postal Code", Int64.Type}},
                        {{"Region", type text}},
                        {{"Product ID", type text}},
                        {{"Category", type text}},
                        {{"Sub-Category", type text}},
                        {{"Product Name", type text}},
                        {{"Sales", type number}},
                        {{"Quantity", Int64.Type}},
                        {{"Discount", type number}},
                        {{"Profit", type number}}
                    }})
                in
                    ChangedTypes

        column 'Row ID'
            dataType: int64
            isHidden: true
            formatString: 0
            lineageTag: c1ef293b-9452-4f82-a75e-e42ed15e2bc0
            summarizeBy: none
            sourceColumn: Row ID

        column 'Order ID'
            dataType: string
            lineageTag: 292f3e50-0f1a-402b-b9af-fd982e748d17
            summarizeBy: none
            sourceColumn: Order ID

        column 'Order Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 9f7a277a-fff9-430b-9377-249c7a322161
            summarizeBy: none
            sourceColumn: Order Date

        column 'Ship Date'
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 98394c3e-8712-4c7e-a55d-68d86177fe30
            summarizeBy: none
            sourceColumn: Ship Date

        column 'Ship Mode'
            dataType: string
            lineageTag: bc8cd871-aa25-4783-beb3-2d6b89a9124b
            summarizeBy: none
            sourceColumn: Ship Mode

        column 'Customer ID'
            dataType: string
            lineageTag: a87c45fb-e5f1-4c26-ae9c-6dd17c237f9c
            summarizeBy: none
            sourceColumn: Customer ID

        column Segment
            dataType: string
            lineageTag: 5ea0e327-90de-4794-8d23-bf1812ae7c53
            summarizeBy: none
            sourceColumn: Segment

        column Country
            dataType: string
            lineageTag: 067ebd7c-3ca1-49b4-a2d9-af33bd4102b6
            summarizeBy: none
            sourceColumn: Country

        column City
            dataType: string
            lineageTag: 116f201f-693c-41ec-84d9-89e1b5674ea9
            summarizeBy: none
            sourceColumn: City

        column State
            dataType: string
            lineageTag: bef795ea-5820-4db3-8e2f-0fdeae447aa3
            summarizeBy: none
            sourceColumn: State

        column 'Postal Code'
            dataType: int64
            formatString: 0
            lineageTag: 48913be9-b7d6-4d17-8bca-fd4723c434bb
            summarizeBy: none
            sourceColumn: Postal Code

        column Region
            dataType: string
            lineageTag: e07ee5d7-d714-46b3-afe8-03a31bb90824
            summarizeBy: none
            sourceColumn: Region

        column 'Product ID'
            dataType: string
            lineageTag: de1b3825-f420-4229-9591-ffc4206512f8
            summarizeBy: none
            sourceColumn: Product ID

        column Category
            dataType: string
            lineageTag: f7b1ab28-278d-4df9-bbd8-3eae117a3f53
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: c7b9a5a2-f118-4e60-8c64-a5d2709e333d
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: 998b9a1c-002f-4570-b51f-4dd0a67d4e78
            summarizeBy: none
            sourceColumn: Product Name

        column Sales
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: ddbe44c0-7cd5-4ee8-a448-873d23e2929a
            summarizeBy: sum
            sourceColumn: Sales

        column Quantity
            dataType: int64
            formatString: 0
            lineageTag: a6e74e5b-1996-4e1b-8aa9-0bb76cc7ba6c
            summarizeBy: sum
            sourceColumn: Quantity

        column Discount
            dataType: double
            formatString: 0.00%
            lineageTag: 938c56ec-d3d0-4821-8911-0c467932aa8b
            summarizeBy: average
            sourceColumn: Discount

        column Profit
            dataType: double
            formatString: \$#,0.00;(\$#,0.00);\$#,0.00
            lineageTag: b6b18eb8-fc8b-40f6-950b-ac378dc35ec3
            summarizeBy: sum
            sourceColumn: Profit

        // --- Calculated Column: Logic 400 ---
        // Tableau: [Sales] < 400 (boolean)
        column 'Logic 400'
            dataType: boolean
            lineageTag: 85335c14-f85b-49ae-89c5-4f593dd1a2c4
            summarizeBy: none
            isDataTypeInferred: true
            expression: IF(Orders[Sales] < 400, TRUE(), FALSE())

    // ===========================================
    // DIMENSION TABLE: Customers
    // ===========================================

    table Customers
        lineageTag: f10d20d2-e409-4a09-bd4f-860c90af8e86

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Customer ID", type text}},
                        {{"Customer Name", type text}}
                    }})
                in
                    ChangedTypes

        column 'Customer ID'
            dataType: string
            lineageTag: 5f76e214-830c-4e7c-858b-048e91cede6f
            summarizeBy: none
            sourceColumn: Customer ID
            isKey: true

        column 'Customer Name'
            dataType: string
            lineageTag: dd464de4-354b-4097-a038-90aeafa82be6
            summarizeBy: none
            sourceColumn: Customer Name

    // ===========================================
    // DIMENSION TABLE: Products
    // ===========================================

    table Products
        lineageTag: 11bcc527-1fe1-4489-8695-1050668860cb

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{
                        {{"Product ID", type text}},
                        {{"Category", type text}},
                        {{"Sub-Category", type text}},
                        {{"Product Name", type text}}
                    }})
                in
                    ChangedTypes

        column 'Product ID'
            dataType: string
            lineageTag: 54dc47ec-e926-4bc3-a1f0-2f044a01ec84
            summarizeBy: none
            sourceColumn: Product ID
            isKey: true

        column Category
            dataType: string
            lineageTag: bff09a5e-f392-4ec9-9ff4-1c637d27dd0c
            summarizeBy: none
            sourceColumn: Category

        column 'Sub-Category'
            dataType: string
            lineageTag: bd2658af-d7cb-4cbf-8752-41e8da12bd11
            summarizeBy: none
            sourceColumn: Sub-Category

        column 'Product Name'
            dataType: string
            lineageTag: 701da01f-57ed-4f7e-9439-ec61d6e21035
            summarizeBy: none
            sourceColumn: Product Name

    // ===========================================
    // DATE TABLE (DAX-generated calendar)
    // ===========================================

    table Date
        lineageTag: 9e98f9e4-f19f-4b87-8e11-b145dc7bc2d2

        partition Date = calculated
            mode: import
            source = CALENDAR(DATE(2020,1,1), DATE(2023,12,31))

        column Date
            dataType: dateTime
            formatString: dd/MM/yyyy
            lineageTag: 23f9f1bb-014a-458d-b864-fe43a2ab74f0
            summarizeBy: none
            isKey: true

        column Year
            dataType: int64
            formatString: 0
            lineageTag: 0bc40e14-be2f-4089-87a0-0b4150817409
            summarizeBy: none
            isDataTypeInferred: true
            expression: YEAR([Date])

        column Month
            dataType: int64
            formatString: 0
            lineageTag: f1e3cd8f-fbad-43b3-8cef-937f2890f1c8
            summarizeBy: none
            isDataTypeInferred: true
            expression: MONTH([Date])

        column 'Month Name'
            dataType: string
            lineageTag: c6b1ea1b-4dd3-4532-b470-14aa2843573e
            summarizeBy: none
            isDataTypeInferred: true
            expression: FORMAT([Date], "MMMM")

        column Quarter
            dataType: string
            lineageTag: 16a1340b-d2fd-485a-a422-ec363ecc0cb0
            summarizeBy: none
            isDataTypeInferred: true
            expression: "Q" & FORMAT([Date], "Q")

    // ===========================================
    // RELATIONSHIPS
    // ===========================================

    relationship Orders_Customers
        fromTable: Orders
        fromColumn: 'Customer ID'
        toTable: Customers
        toColumn: 'Customer ID'
        crossFilteringBehavior: singleDirection

    relationship Orders_Products
        fromTable: Orders
        fromColumn: 'Product ID'
        toTable: Products
        toColumn: 'Product ID'
        crossFilteringBehavior: singleDirection

    relationship Orders_Date
        fromTable: Orders
        fromColumn: 'Order Date'
        toTable: Date
        toColumn: Date
        crossFilteringBehavior: singleDirection
