-- Part 3: the three analyst questions, answered as SQL against the same Postgres database.
-- These are the queries behind part3-data-analyst/answers.md (generated by scripts/analyst_answers.py).

-- Q1 (lookup): top 10 customers by profit last year (2023)
SELECT profit_rank, customer_name, segment, sales, profit, orders
FROM analytics.top_customers
WHERE year = 2023 AND profit_rank <= 10
ORDER BY profit_rank;

-- Q2 (trend): monthly sales by region
SELECT month, region, sales
FROM analytics.monthly_sales
WHERE month >= DATE '2023-01-01'
ORDER BY month, region;

-- Q3 (why): why did profit drop in the Central region in Q4 2023?
-- Step 1: did it drop? Central profit by quarter, 2023 vs 2022.
SELECT EXTRACT(year FROM order_date)::int AS year, EXTRACT(quarter FROM order_date)::int AS quarter,
       round(SUM(sales)) AS sales, round(SUM(profit)) AS profit, round(AVG(discount)::numeric, 3) AS avg_discount
FROM analytics.order_lines
WHERE region = 'Central' AND order_date >= DATE '2022-01-01'
GROUP BY 1, 2 ORDER BY 1, 2;

-- Step 2: which sub-categories drove the change? Q4 2023 vs Q4 2022 (Central only).
WITH q AS (
  SELECT sub_category,
         SUM(CASE WHEN EXTRACT(year FROM order_date) = 2023 THEN profit END) AS profit_q4_2023,
         SUM(CASE WHEN EXTRACT(year FROM order_date) = 2022 THEN profit END) AS profit_q4_2022,
         AVG(CASE WHEN EXTRACT(year FROM order_date) = 2023 THEN discount END) AS disc_2023
  FROM analytics.order_lines
  WHERE region = 'Central' AND EXTRACT(quarter FROM order_date) = 4
  GROUP BY 1)
SELECT sub_category, round(COALESCE(profit_q4_2023, 0)) AS profit_q4_2023, round(COALESCE(profit_q4_2022, 0)) AS profit_q4_2022,
       round(COALESCE(profit_q4_2023, 0) - COALESCE(profit_q4_2022, 0)) AS delta, round(COALESCE(disc_2023, 0)::numeric, 2) AS avg_discount_2023
FROM q ORDER BY delta;

-- Step 3: is Central's discounting unusual? Average discount and margin by region, 2023.
SELECT region, round(AVG(discount)::numeric, 3) AS avg_discount, round((SUM(profit) / SUM(sales))::numeric, 3) AS margin
FROM analytics.order_lines WHERE EXTRACT(year FROM order_date) = 2023
GROUP BY 1 ORDER BY avg_discount DESC;

-- Step 4: the individual order lines that lost the most money in Central, Q4 2023.
SELECT order_date, customer_name, sub_category, product_name, round(sales) AS sales, discount, round(profit) AS profit
FROM analytics.order_lines
WHERE region = 'Central' AND order_date BETWEEN DATE '2023-10-01' AND DATE '2023-12-31'
ORDER BY profit LIMIT 10;
