// TMDL Semantic Model — Section 13: Multi-Measures
// Generated from .twb XML source
// This workbook uses Measure Names/Values pattern (no calculated fields)

model Model
    culture: en-US

    table Orders
        lineageTag: orders-multi-measures
        dataCategory: Regular

        partition Orders = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Orders.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
                        {"Order_ID", type text},
                        {"Customer_ID", type text},
                        {"Product_ID", type text},
                        {"Order_Date", type date},
                        {"Shipping_Date", type date},
                        {"Sales", type number},
                        {"Quantity", Int64.Type},
                        {"Discount", type number},
                        {"Profit", type number},
                        {"Unit_Price", type number}
                    })
                in
                    ChangedTypes

        column 'Order ID' = Orders[Order_ID]
            dataType: string
        column 'Customer ID' = Orders[Customer_ID]
            dataType: string
        column 'Product ID' = Orders[Product_ID]
            dataType: string
        column 'Order Date' = Orders[Order_Date]
            dataType: dateTime
            formatString: dd/MM/yyyy
        column 'Ship Date' = Orders[Shipping_Date]
            dataType: dateTime
            formatString: dd/MM/yyyy
        column Sales
            dataType: decimal
            formatString: #,##0.00
        column Quantity
            dataType: int64
        column Discount
            dataType: decimal
        column Profit
            dataType: decimal
            formatString: #,##0.00
        column 'Unit Price' = Orders[Unit_Price]
            dataType: decimal
        column Category
            dataType: string
        column 'Sub-Category'
            dataType: string
        column 'Product Name'
            dataType: string
        column Country
            dataType: string
        column Region
            dataType: string

        // Standard aggregate measures
        measure 'Total Sales' = SUM(Orders[Sales])
            formatString: #,##0.00
        measure 'Total Profit' = SUM(Orders[Profit])
            formatString: #,##0.00
        measure 'Total Quantity' = SUM(Orders[Quantity])
        measure 'Total Discount' = SUM(Orders[Discount])
            formatString: 0.00%

    table Customers
        lineageTag: customers-multi-measures

        partition Customers = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Customers.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
                in
                    PromotedHeaders

        column 'Customer ID' = Customers[Customer_ID]
            dataType: string
        column 'First Name' = Customers[First_Name]
            dataType: string
        column 'Last Name' = Customers[Last_Name]
            dataType: string
        column Country
            dataType: string

    table Products
        lineageTag: products-multi-measures

        partition Products = m
            mode: import
            source =
                let
                    Source = Csv.Document(File.Contents("course/datasets/non-eu-dataset/small-dataset/Products.csv"), [Delimiter=";", Encoding=65001]),
                    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
                in
                    PromotedHeaders

        column 'Product ID' = Products[Product_ID]
            dataType: string
        column 'Product Name' = Products[Product_Name]
            dataType: string
        column Category
            dataType: string
        column 'Sub-Category'
            dataType: string

    // Field Parameter table for combined-axis visuals
    // NOTE: Create this via Modeling > New Parameter > Fields in Power BI Desktop
    // table MeasureSelector
    //     isFieldParameter: true
    //     columns: MeasureSelector, MeasureSelector Fields, MeasureSelector Order
    //     rows:
    //         ("Sales", NAMEOF('Orders'[Sales]), 0)
    //         ("Profit", NAMEOF('Orders'[Profit]), 1)
    //         ("Quantity", NAMEOF('Orders'[Quantity]), 2)
    //         ("Discount", NAMEOF('Orders'[Discount]), 3)

    // Relationships
    relationship Orders_Customers = Orders[Customer ID] -> Customers[Customer ID]
        crossFilteringBehavior: singleDirection

    relationship Orders_Products = Orders[Product ID] -> Products[Product ID]
        crossFilteringBehavior: singleDirection
